"""The 48 laws — original LEVI-native strategic doctrine.

Each law is one object: forward play + reverse play + constraints + signals.
Doctrine: defense never manipulates; attack = going and getting the goal.
Nothing here is borrowed from any published list of laws.
"""

from __future__ import annotations

from typing import List, Tuple

from . import Law


DOMAINS = {
    1: ("relationships", "negotiation", "work", "community"),
    2: ("work", "business", "goals", "daily"),
    3: ("money", "goals", "health", "work"),
    4: ("work", "negotiation", "business", "learning"),
    5: ("work", "goals", "relationships", "business"),
    6: ("work", "business", "learning", "money"),
    7: ("business", "goals", "work", "learning"),
    8: ("goals", "work", "health", "daily"),
    9: ("negotiation", "relationships", "money", "conflict"),
    10: ("work", "business", "relationships", "learning"),
    11: ("business", "money", "relationships", "work"),
    12: ("learning", "health", "work", "goals"),
    13: ("money", "work", "relationships", "business"),
    14: ("health", "goals", "learning", "daily"),
    15: ("self", "goals", "work", "relationships"),
    16: ("negotiation", "work", "conflict", "daily"),
    17: ("learning", "work", "money", "health"),
    18: ("goals", "work", "relationships", "daily"),
    19: ("relationships", "work", "community", "family"),
    20: ("negotiation", "business", "conflict", "work"),
    21: ("money", "health", "work", "daily"),
    22: ("business", "work", "money", "goals"),
    23: ("community", "work", "relationships", "family"),
    24: ("money", "health", "learning", "goals"),
    25: ("work", "business", "relationships", "community"),
    26: ("work", "business", "health", "learning"),
    27: ("work", "daily", "goals", "relationships"),
    28: ("relationships", "work", "family", "community"),
    29: ("health", "work", "conflict", "daily"),
    30: ("work", "relationships", "community", "learning"),
    31: ("negotiation", "money", "conflict", "business"),
    32: ("business", "work", "community", "goals"),
    33: ("work", "learning", "business", "goals"),
    34: ("negotiation", "relationships", "business", "work"),
    35: ("money", "work", "business", "goals"),
    36: ("business", "money", "goals", "community"),
    37: ("negotiation", "money", "conflict", "work"),
    38: ("money", "work", "health", "relationships"),
    39: ("negotiation", "relationships", "family", "work"),
    40: ("money", "health", "work", "family"),
    41: ("relationships", "work", "goals", "business"),
    42: ("money", "business", "learning", "goals"),
    43: ("work", "business", "relationships", "community"),
    44: ("health", "work", "goals", "learning"),
    45: ("work", "learning", "community", "business"),
    46: ("goals", "health", "relationships", "work"),
    47: ("work", "goals", "business", "learning"),
    48: ("self", "goals", "work", "daily"),
}


def _L(law_id: int, name: str, doctrine: str, forward: str, reverse: str,
       constraints: Tuple[str, ...], signals: Tuple[str, ...]) -> Law:
    return Law(id=law_id, name=name, doctrine=doctrine, forward=forward,
               reverse=reverse, constraints=constraints, signals=signals,
               domains=DOMAINS.get(law_id, ()))


def build_laws() -> List[Law]:
    return [
        _L(1, "The Open Hand",
           "Strength shown plainly needs no disguise.",
           "Declare intent openly when trust is the currency; transparency compounds into alliance.",
           "When the field rewards predators, keep the hand open but the cards close — show the intent, never the inventory.",
           ("Never confuse openness with exposure.", "The open hand still guards the critical piece."),
           ("trust", "transparency", "alliance", "honesty", "negotiation")),
        _L(2, "First Light",
           "The empty field belongs to whoever arrives first.",
           "Move first when the field is open; early position is cheap and compounds.",
           "When the field is crowded and watched, move last — let others spend themselves, then take the shaped ground.",
           ("First is only an advantage if you can hold it.", "Don't rush into a trap to be early."),
           ("initiative", "timing", "first", "early", "opportunity")),
        _L(3, "The Long Ledger",
           "Play for the account that compounds.",
           "Choose the move that pays in years, not days; reputation and position accrue.",
           "When the horizon collapses and a window is closing, spend the ledger — cash in position for the one decisive move.",
           ("The ledger is real only if you can afford the wait.", "Never mortgage survival for the long term."),
           ("long-term", "patience", "investment", "compounding", "future")),
        _L(4, "High Ground",
           "Hold the position that sees furthest.",
           "Occupy the vantage — information, timing, terrain — before any contest begins.",
           "When high ground is taken, go low and move: speed and invisibility beat altitude.",
           ("Vantage without the ability to act on it is scenery.",),
           ("position", "advantage", "vantage", "information", "terrain")),
        _L(5, "The Clean Cut",
           "End what is finished.",
           "Close dead efforts fast; sunk cost is a tax on the future.",
           "When a thing is nearly alive, protect the last mile — never cut an inch from harvest.",
           ("Cut the effort, not the lesson — compost it.", "Be sure it is dead, not dormant."),
           ("quit", "sunk cost", "end", "pivot", "failure")),
        _L(6, "Borrowed Fire",
           "Use what already burns.",
           "Stand on ready tools, allies' strength, and proven roads instead of building everything.",
           "When dependence becomes a leash, build your own fire — own the critical piece outright.",
           ("Borrowed fire still needs your own spark.", "Never borrow what you cannot return."),
           ("leverage", "tools", "allies", "resources", "dependence")),
        _L(7, "The Quiet Build",
           "Grow before you announce.",
           "Build in silence until the work can defend itself; premature light invites premature attack.",
           "When silence reads as absence, announce early and recruit the crowd to your build.",
           ("Silence is strategy, not fear.", "The quiet build still needs one witness."),
           ("stealth", "launch", "announce", "build", "secrecy")),
        _L(8, "One True North",
           "A single decisive aim concentrates all force.",
           "Concentrate everything on one goal; scattered effort scatters results.",
           "When the north is blocked, carry two aims — the visible one, and the one that actually moves.",
           ("One aim, not one method.", "The north must be yours, not assigned."),
           ("focus", "goal", "priority", "aim", "concentration")),
        _L(9, "The Patient Stone",
           "Outlast what you cannot outfight.",
           "When time is your ally, wait; pressure decays and position grows.",
           "When time is the enemy's ally, compress — act before the window seals.",
           ("Patience is active: prepare while you wait.", "Waiting without a trigger is drifting."),
           ("patience", "waiting", "endurance", "timing", "outlast")),
        _L(10, "Visible Work",
           "Let the work be seen doing the work.",
           "Demonstrate, don't describe; evidence persuades where claims annoy.",
           "When the audience punishes success, work visibly on the small thing while the real work stays covered.",
           ("Visibility serves the work, never the ego.",),
           ("show", "demonstrate", "proof", "evidence", "portfolio")),
        _L(11, "The Fair Trade",
           "Every alliance priced honestly.",
           "Trade value for value; clean deals compound into networks that carry you.",
           "When the other side trades in favors and fog, price everything in writing — convert fog to contract.",
           ("Fair does not mean equal — it means explicit.",),
           ("deal", "alliance", "partnership", "trade", "contract")),
        _L(12, "Deep Roots",
           "Master the fundamentals; depth beats novelty.",
           "The master of basics beats the collector of tricks every time.",
           "When the game itself changes, unlearn fast — root in method, not in tools.",
           ("Depth first, breadth second.", "Fundamentals are boring until they save you."),
           ("mastery", "fundamentals", "skill", "learning", "basics")),
        _L(13, "The Second Door",
           "Always keep an exit — until commitment is the weapon.",
           "Enter every commitment with the way out mapped; optionality is survival.",
           "When the exit becomes the excuse, burn the second door — total commitment is the weapon.",
           ("Know which door you would take before you enter.",),
           ("exit", "options", "commitment", "risk", "escape")),
        _L(14, "Small Wins, Stacked",
           "Momentum is manufactured, one win at a time.",
           "Chain small victories; each one funds the next and teaches the pattern.",
           "When small wins become a treadmill, stop and take the one big swing the stack earned.",
           ("Small wins must stack toward the goal, not sideways.",),
           ("momentum", "progress", "wins", "habit", "streak")),
        _L(15, "The Honest Mirror",
           "Measure yourself without flattery.",
           "Audit your position coldly; delusion is the only unbeatable enemy.",
           "When the mirror becomes a weapon against you, measure by trajectory, not position — direction over snapshot.",
           ("The mirror informs; it does not sentence.",),
           ("self-assessment", "honesty", "feedback", "audit", "weakness")),
        _L(16, "Tempo",
           "Control the speed of the game.",
           "Set a pace others must match; whoever sets tempo sets terms.",
           "When the tempo is forced on you, break rhythm — pause, accelerate, change the game.",
           ("Tempo serves the goal; speed for its own sake is panic.",),
           ("pace", "speed", "rhythm", "timing", "control")),
        _L(17, "The Wide Net",
           "Gather more than you need before you decide.",
           "Listen broadly before deciding; the best move is usually in the data you almost ignored.",
           "When drowning in signal, narrow to one question — the decision that unblocks all others.",
           ("Net wide, decide narrow.", "Information is not action."),
           ("research", "information", "data", "intelligence", "learn")),
        _L(18, "Named Things",
           "Define before you act.",
           "Name the goal, the problem (never the person), and the win condition — clarity is force.",
           "When naming it early lets others block it, act first and name it after.",
           ("Name the problem, not the person.", "A vague name is a vague war."),
           ("clarity", "define", "goal-setting", "planning", "framing")),
        _L(19, "The Steady Signal",
           "Predictable to allies, unreadable to the field.",
           "Consistency builds the trust that compounds into loyalty.",
           "When predictability is being exploited, vary the pattern — keep the promise, change the path.",
           ("Steadiness is reliability, not rigidity.",),
           ("consistency", "trust", "reliability", "reputation", "habit")),
        _L(20, "Own the Frame",
           "Whoever defines the contest usually wins it.",
           "Set the terms, the arena, the criteria — play your game, not theirs.",
           "When the frame is rigged, refuse the contest — build your own arena.",
           ("Frames are tools, not truths.", "Never accept a frame you didn't inspect."),
           ("framing", "negotiation", "terms", "arena", "rules")),
        _L(21, "The Spare Key",
           "Redundancy in all critical things.",
           "Two ways to win, two sources of every critical resource; single points of failure are invitations.",
           "When redundancy spreads you thin, pick the one key and guard it with everything.",
           ("Redundancy in the critical, not in everything.",),
           ("backup", "redundancy", "plan b", "resilience", "risk")),
        _L(22, "Strike the Iron",
           "Act when conditions are hot.",
           "When alignment appears, move fully — hesitation wastes rare windows.",
           "When the iron is cold, prepare: sharpen, stockpile, rehearse — so the strike is instant when it heats.",
           ("Hot iron still needs aim.", "Don't mistake warmth for heat."),
           ("action", "opportunity", "timing", "decisive", "window")),
        _L(23, "The Empty Chair",
           "Leave room for others to join the win.",
           "Design victories others can share; shared wins recruit future allies.",
           "When the chair fills with freeloaders, charge admission — contribution is the ticket.",
           ("The chair is for contributors, not spectators.",),
           ("collaboration", "team", "recruit", "shared", "community")),
        _L(24, "Compound Interest",
           "Small edges, relentlessly applied.",
           "One percent better every cycle; the math does the fighting for you.",
           "When compounding is too slow for the deadline, concentrate — one fifty-percent leap beats fifty one-percent steps.",
           ("Compounding needs time; check the clock.",),
           ("growth", "incremental", "improvement", "compounding", "habit")),
        _L(25, "The Clean Name",
           "Reputation is a weapon you never have to draw.",
           "Protect the name; it opens doors force cannot and outlasts every campaign.",
           "When the name is under attack, answer with work, not words — evidence is the only rebuttal.",
           ("The name is built in drops, lost in buckets.",),
           ("reputation", "credibility", "trust", "brand", "honor", "attack", "smear", "undermined")),
        _L(26, "Terrain Reading",
           "Fight where you are strongest.",
           "Choose ground that favors you — your skills, your tools, your rules.",
           "When you must fight on hostile ground, change what 'ground' means — move the contest to your domain.",
           ("Know the terrain before you need it.",),
           ("strengths", "environment", "context", "advantage", "positioning")),
        _L(27, "The Decisive No",
           "Refusal is a strategy.",
           "No to everything that isn't the goal; focus is subtraction.",
           "When 'no' closes the only door, say yes strategically — one yes that buys ten future nos.",
           ("Every yes is a thousand nos.", "No without a reason is just fear."),
           ("focus", "boundaries", "say no", "priority", "decline")),
        _L(28, "Allies, Not Pawns",
           "People are ends, never instruments.",
           "Invest in people with no extraction plan; loyalty given freely returns multiplied.",
           "When loyalty is demanded as tribute, the alliance is already dead — exit cleanly.",
           ("Never manipulate; the doctrine forbids it.", "Gratitude is a strategy with no downside."),
           ("relationships", "loyalty", "team", "people", "allies", "betrayed", "provoked")),
        _L(29, "The Rehearsed Mind",
           "Decide before the moment arrives.",
           "Pre-decide your moves for likely scenarios; the calm mind is the prepared mind.",
           "When the moment breaks the script, improvise from principle — the plan was training, not chains.",
           ("Rehearse the decision, not just the action.",),
           ("preparation", "planning", "scenarios", "calm", "readiness")),
        _L(30, "Visible Scars",
           "Own your failures; the composted failure is credibility.",
           "Name what went wrong and what it taught; failure digested is authority.",
           "When the field weaponizes honesty, compost privately — the lesson still lands, the scar stays covered.",
           ("Own the failure, never the shame.", "Scars are proof of healing, not of damage."),
           ("failure", "mistakes", "accountability", "lessons", "vulnerability", "blamed", "accused")),
        _L(31, "The Long Game Face",
           "Never show the clock.",
           "Act as if time is infinite; urgency leaks leverage.",
           "When the deadline is your weapon, show the clock — manufactured urgency moves others.",
           ("The face is calm; the plan has a clock.",),
           ("negotiation", "patience", "leverage", "deadline", "composure")),
        _L(32, "Build the Table",
           "Don't beg for a seat — build the table.",
           "Create the platform, the market, the venue; hosts set the rules.",
           "When building the table costs the war, take the best seat at theirs — and outplay from inside.",
           ("The table serves a goal, not an ego.",),
           ("platform", "create", "leadership", "initiative", "ownership")),
        _L(33, "The Sharp Edge",
           "Be undeniably good at one thing.",
           "Excellence in one domain is a moat no tactic crosses.",
           "When the edge dulls and the domain commoditizes, transfer the sharpness — the discipline, not the skill.",
           ("One edge, honed daily.", "Sharpness is maintenance, not talent."),
           ("excellence", "expertise", "skill", "mastery", "niche")),
        _L(34, "Fog and Lantern",
           "Reveal selectively: share the map, keep the route.",
           "Be transparent about aims and private about methods; aims recruit, methods are the moat.",
           "When fog is mistaken for deceit, go full lantern — radical openness as the disarming move.",
           ("Fog hides method, never motive.",),
           ("transparency", "privacy", "openness", "strategy", "trust")),
        _L(35, "Hunter and Farmer",
           "Choose your tempo of gain.",
           "Hunt when the prize is rare and mobile — commit fully to the chase.",
           "When hunting exhausts, farm — plant systems that yield while you sleep.",
           ("Know which season you're in.", "The farmer still hunts the weeds."),
           ("strategy", "systems", "pursuit", "passive", "effort")),
        _L(36, "Stone Soup",
           "Start with what you have; momentum attracts the rest.",
           "Begin visibly with little; motion recruits contribution better than plans recruit permission.",
           "When the pot fills with others' ingredients and none of yours, reclaim the recipe — own the core.",
           ("Start ugly; start now.", "The stone is yours; the soup is shared."),
           ("start", "resourceful", "bootstrap", "momentum", "begin")),
        _L(37, "The Unplayed Card",
           "Keep one move in reserve.",
           "Never spend your last option; the reserve is the real power.",
           "When holding back loses the moment, play it all — the card unplayed in the decisive hand is worthless.",
           ("The reserve is for the decisive moment, not for comfort.",),
           ("reserve", "options", "leverage", "backup", "all-in")),
        _L(38, "Measure Twice",
           "Verify before you trust.",
           "Check the critical facts yourself; the cost of verification is always less than the cost of betrayal by assumption.",
           "When verification costs the opportunity, trust the pattern — bet on the base rate, not the audit.",
           ("Verify the critical, trust the trivial.",),
           ("verify", "due diligence", "facts", "trust", "check")),
        _L(39, "The Common Ground",
           "Find the shared win.",
           "Frame every proposal as their victory too; adoption follows interest.",
           "When common ground is a trap — their win requires your loss — name the conflict plainly and negotiate from strength.",
           ("Shared wins must be real, not painted.",),
           ("win-win", "negotiation", "agreement", "persuasion", "shared")),
        _L(40, "Winter Stores",
           "Prepare in plenty for scarcity.",
           "Stockpile cash, skills, and goodwill in good seasons; winter always comes.",
           "When winter arrives unprepared, trade boldly — scarcity makes the bold move cheap.",
           ("Stores are for winter, not for hoarding.",),
           ("prepare", "savings", "resilience", "scarcity", "buffer")),
        _L(41, "The Clean Break",
           "Leave without residue.",
           "Exit failing ventures, toxic ties, and dead ends completely — residue drags the next campaign.",
           "When the bridge is worth more than the exit, leave the door open — depart without burning.",
           ("Break clean or don't break.", "The break is from the pattern, not always the person."),
           ("leave", "exit", "boundaries", "toxic", "end", "bullying", "humiliated")),
        _L(42, "Many Small Bets",
           "Diversify the attack; let winners emerge.",
           "Spread small experiments; the field tells you which bet was right.",
           "When one bet is clearly the winner, go all in — diversification past clarity is cowardice.",
           ("Bets are small enough to lose.", "Listen to the results, not your hopes."),
           ("experiment", "diversify", "bets", "test", "options")),
        _L(43, "The Storyteller",
           "Narrative moves what logic cannot.",
           "Wrap the goal in a story people can carry; stories recruit where arguments merely convince.",
           "When story becomes spin, strip to facts — the numbers, told plain, are the stronger story.",
           ("Story serves truth; spin serves the teller.", "Never let the story outrun the work."),
           ("story", "narrative", "persuasion", "communication", "message")),
        _L(44, "The Anvil",
           "Let pressure forge you.",
           "Seek the hard contest; resistance builds the edge that comfort never will.",
           "When the hammer is senseless destruction, leave the forge — not every pressure is productive.",
           ("Choose your anvils.", "Rest is part of forging."),
           ("resilience", "hardship", "growth", "challenge", "pressure")),
        _L(45, "Gatekeeping Inverted",
           "Open what others close.",
           "Publish, teach, share — openness builds the network that closed gates envy.",
           "When openness is strip-mined, close the gate on the extractors — open to builders, closed to miners.",
           ("Openness is a strategy, not a sacrifice.",),
           ("open", "share", "teach", "generosity", "network")),
        _L(46, "The Oath",
           "Bind yourself to the goal publicly.",
           "Declared commitment recruits help and kills the retreat you would otherwise take.",
           "When the oath binds you to a dead goal, release it ritually — the clean break, witnessed.",
           ("Oaths are to goals, not to methods.", "Never swear what you cannot keep."),
           ("commitment", "accountability", "promise", "declare", "vow")),
        _L(47, "The Last Mile",
           "Finish what you start.",
           "Completion is the rarest skill; the final ten percent is the whole reputation.",
           "When the last mile costs more than the goal is worth, abandon at ninety — the sunk-cost law inverts.",
           ("Finish or formally release — nothing lingers.",),
           ("finish", "complete", "follow-through", "discipline", "done")),
        _L(48, "The Living Law",
           "No law stands above the goal rightly held.",
           "Every law here serves the aim; break any of them when the goal demands it — the engine is a servant, not a master.",
           "When breaking laws becomes the habit, return to the code — discipline is the difference between strategy and drift.",
           ("The goal must be rightly held — check it in the mirror.", "Law 48 never excuses Law 28."),
           ("meta", "principles", "discipline", "judgment", "wisdom")),
    ]
