"""Shared RS256 JWT key management for the VYVE backend services.

Both the OAuth provider (issuer) and the messaging service (verifier) import
this module so they always agree on the signing key, even though they run as
separate processes.

Key resolution order:
  1. ``VYVE_JWT_PRIVATE_KEY_PEM`` env var — an RSA private key in PEM format.
     Use this in production (injected via your secret manager).
  2. Otherwise a private PEM is loaded from / generated into
     ``VYVE_KEY_DIR`` (default ``~/.vyve/keys/vyve-rs256.pem``). The generated
     file is written with mode 0o600. Both server processes share the default
     directory, so a key generated by the first process to start is reused by
     the second — no hardcoded secret is shipped.

Key rotation procedure: replace the PEM file (or the env var) with the new
key and restart both services. Tokens signed with the old key stop verifying
immediately; for a graceful rotation, briefly publish the old public key in
the JWKS alongside the new one, wait out the longest access-token lifetime,
then remove the old key.

Only the PUBLIC key is ever published (see :func:`public_jwk`). Never log,
print, or expose the private key material.
"""

from __future__ import annotations

import base64
import os
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

JWT_ALGORITHM = "RS256"
JWT_KID = "vyve-1"
_KEY_FILENAME = "vyve-rs256.pem"

_private_key: rsa.RSAPrivateKey | None = None


def _key_dir() -> Path:
    return Path(
        os.getenv("VYVE_KEY_DIR", os.path.join(os.path.expanduser("~"), ".vyve", "keys"))
    ).expanduser()


def _load_env_key() -> rsa.RSAPrivateKey | None:
    pem = os.getenv("VYVE_JWT_PRIVATE_KEY_PEM")
    if not pem:
        return None
    key = serialization.load_pem_private_key(pem.encode("utf-8"), password=None)
    if not isinstance(key, rsa.RSAPrivateKey):
        raise RuntimeError("VYVE_JWT_PRIVATE_KEY_PEM must be an RSA private key PEM")
    return key


def _load_or_generate_key() -> rsa.RSAPrivateKey:
    """Load the persisted key, or generate an RSA-2048 pair and persist it."""
    key_dir = _key_dir()
    key_path = key_dir / _KEY_FILENAME
    if key_path.exists():
        key = serialization.load_pem_private_key(key_path.read_bytes(), password=None)
        if not isinstance(key, rsa.RSAPrivateKey):
            raise RuntimeError(f"JWT key at {key_path} is not an RSA private key")
        return key

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    key_dir.mkdir(parents=True, exist_ok=True)
    # Write atomically-ish and restrict permissions: the private key must not
    # be readable by other users.
    tmp_path = key_dir / (_KEY_FILENAME + ".tmp")
    with open(tmp_path, "wb") as f:
        f.write(pem)
    os.chmod(tmp_path, 0o600)
    os.replace(tmp_path, key_path)
    os.chmod(key_path, 0o600)
    return key


def get_private_key() -> rsa.RSAPrivateKey:
    """Return the RSA private key used for signing (cryptography key object)."""
    global _private_key
    if _private_key is None:
        key = _load_env_key() or _load_or_generate_key()
        _private_key = key
    return _private_key


def get_public_key():
    """Return the RSA public key used for verification (cryptography key object)."""
    return get_private_key().public_key()


def get_private_key_pem() -> bytes:
    """Return the private key as PEM bytes (for JWT libraries)."""
    return get_private_key().private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )


def get_public_key_pem() -> bytes:
    """Return the public key as PEM bytes (for JWT libraries)."""
    return get_public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )


def _b64u_int(value: int) -> str:
    raw = value.to_bytes((value.bit_length() + 7) // 8, "big")
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def public_jwk() -> dict:
    """Return the public key as a JWK dict for the JWKS endpoint.

    Contains ONLY public material (kty/n/e). Never includes private or
    symmetric key data.
    """
    numbers = get_public_key().public_numbers()
    return {
        "kty": "RSA",
        "alg": JWT_ALGORITHM,
        "use": "sig",
        "kid": JWT_KID,
        "n": _b64u_int(numbers.n),
        "e": _b64u_int(numbers.e),
    }
