"""Export a canvas's Web layer to honest, tracking-free HTML and SVG.

HTML: a standalone page with an ``<img usemap>`` + ``<map>`` — the exact
construct Fireworks emitted, minus the Dreamweaver upsell.
SVG: the canvas as interactive vector shapes wrapped in ``<a>`` anchors.

Both exports carry a provenance comment: local-first, no tracking, no
phone-home. All escaping via :mod:`html`; coordinates are integers in the
output so nothing leaks float noise.
"""

from __future__ import annotations

import html

from .model import Canvas, Hotspot

_HONEST_HEAD = (
    "<!-- generated by levi.weblayer — local-first, no tracking, no phone-home -->")


def _ints(coords) -> str:
    return ",".join(str(int(round(c))) for c in coords)


def _html_area(h: Hotspot) -> str:
    # HTML5 image-maps only know four keywords (rect, circle, poly,
    # default); anything else silently degrades to rectangle in browsers.
    # The model's own "ellipse"/"polygon" names therefore map onto the
    # valid keywords: ellipse -> circle at the smaller radius (stays
    # honestly inside the ellipse), polygon -> poly with the same points.
    if h.shape == "rect":
        x, y, w, hh = h.coords
        shape_kw, coords = "rect", _ints([x, y, x + w, y + hh])
    elif h.shape == "ellipse":
        cx, cy, rx, ry = h.coords
        shape_kw, coords = "circle", _ints([cx, cy, min(rx, ry)])
    elif h.shape == "polygon":
        shape_kw, coords = "poly", _ints(h.coords)
    else:
        raise ValueError("weblayer: unknown shape %r for HTML image-map" % (h.shape,))
    alt = html.escape(h.alt or h.label or h.id, quote=True)
    return ('<area shape="%s" coords="%s" href="%s" alt="%s" title="%s" />'
            % (shape_kw, coords, html.escape(h.href, quote=True), alt,
               html.escape(h.label or h.id, quote=True)))


def to_html(canvas: Canvas) -> str:
    """Standalone HTML page with an image-map over the canvas."""
    canvas.validate()
    img = html.escape(canvas.image or "canvas.png", quote=True)
    areas = "\n    ".join(_html_area(h) for h in canvas.hotspots)
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />\n"
        "<title>%s</title>\n</head>\n<body>\n%s\n"
        "<img src=\"%s\" usemap=\"#weblayer\" width=\"%d\" height=\"%d\" "
        "alt=\"%s\" />\n"
        "<map name=\"weblayer\">\n    %s\n</map>\n</body>\n</html>\n"
        % (html.escape(canvas.title), _HONEST_HEAD, img,
           canvas.width, canvas.height, html.escape(canvas.title), areas))


def _svg_shape(h: Hotspot) -> str:
    if h.shape == "rect":
        x, y, w, hh = (int(round(c)) for c in h.coords)
        shape = '<rect x="%d" y="%d" width="%d" height="%d" />' % (x, y, w, hh)
    elif h.shape == "ellipse":
        cx, cy, rx, ry = (int(round(c)) for c in h.coords)
        shape = '<ellipse cx="%d" cy="%d" rx="%d" ry="%d" />' % (cx, cy, rx, ry)
    else:
        pts = " ".join("%d,%d" % (int(round(h.coords[i])), int(round(h.coords[i + 1])))
                       for i in range(0, len(h.coords), 2))
        shape = '<polygon points="%s" />' % pts
    label = html.escape(h.label or h.id)
    return ('<a href="%s"><title>%s</title>%s</a>'
            % (html.escape(h.href, quote=True), label, shape))


def to_svg(canvas: Canvas) -> str:
    """Interactive SVG: hotspot shapes wrapped in <a> anchors."""
    canvas.validate()
    shapes = "\n  ".join(_svg_shape(h) for h in canvas.hotspots)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
        'width="%d" height="%d" role="img" aria-label="%s">\n%s\n  %s\n</svg>\n'
        % (canvas.width, canvas.height, canvas.width, canvas.height,
           html.escape(canvas.title, quote=True), _HONEST_HEAD, shapes))
