"""The Honest Generosity Charter — anti-sly-trade rules for every LEVI feature.

Born from the evening tech-giants hunt (2026-09-16):
  arch-giants-free-basics      — "free" that the giver gatekeeps
  arch-giants-privacy-sandbox  — privacy promises as an ad moat
  arch-giants-x-api-kill       — open platforms with a kill switch
  arch-giants-amazon-rival-harvest — the marketplace that clones its sellers

Each sly trade the giants refuse to give up is inverted here into a
machine-checkable rule. A feature that fails the charter is not a LEVI
feature: fix the design or keep it out. This is the addition the giants
would never ship — a tool that flags their own playbook.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, List, Tuple


# ---------------------------------------------------------------------------
# Manifests
# ---------------------------------------------------------------------------


@dataclass
class GenerosityManifest:
    """A feature's declared design. Every field defaults to the honest side.

    Describe the FEATURE, not the marketing. When in doubt, assume the
    check will be read by someone who distrusts you — because it will be.
    """

    name: str
    # --- the sly trades, all defaulted OFF ---
    has_toll_road: bool = False  # core value gated behind payment/permission
    has_gatekeeper_curation: bool = False  # "free" selection the giver controls
    curation_criteria_disclosed: bool = True  # selection rules user-visible...
    curation_criteria_editable: bool = True  # ...and user-editable
    claims_privacy: bool = False  # markets itself as private
    privacy_verifiable_locally: bool = True  # works with the cable pulled
    reserves_revoke_rights: bool = False  # can pull access users built on
    data_exportable: bool = True  # everything created is user-exportable
    uses_user_data_to_compete: bool = False  # harvest users, then rival them
    has_engagement_metrics: bool = False  # streaks/likes/counts that nudge return
    requires_outbound_data: bool = False  # core function needs data to leave
    labels_free_accurately: bool = True  # "free" states the real trade


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CharterRule:
    id: str
    title: str
    inversion: str  # which sly trade this rule inverts
    check: Callable[[GenerosityManifest], bool] = field(repr=False)

    def passes(self, manifest: GenerosityManifest) -> bool:
        try:
            return bool(self.check(manifest))
        except Exception:
            return False


RULES: Tuple[CharterRule, ...] = (
    CharterRule(
        id="no_toll_road",
        title="No toll road",
        inversion="Free Basics: 'free' access whose menu the giver controls.",
        check=lambda m: not m.has_toll_road,
    ),
    CharterRule(
        id="no_gatekeeper_curation",
        title="No gatekeeper curation",
        inversion="Free Basics: if the feature selects or filters for the "
        "user, the criteria must be disclosed AND user-editable — "
        "generosity with a hidden menu is gatekeeping.",
        check=lambda m: (
            not m.has_gatekeeper_curation
            or (m.curation_criteria_disclosed and m.curation_criteria_editable)
        ),
    ),
    CharterRule(
        id="no_privacy_theater",
        title="No privacy theater",
        inversion="Privacy Sandbox: a feature that claims privacy must be "
        "locally verifiable — it must function with the network cable "
        "pulled and no trusted third party.",
        check=lambda m: not m.claims_privacy or m.privacy_verifiable_locally,
    ),
    CharterRule(
        id="no_kill_switch",
        title="No kill switch",
        inversion="X API kill: never reserve the right to revoke access "
        "users built on; everything the feature creates must be "
        "user-exportable from day one.",
        check=lambda m: not m.reserves_revoke_rights and m.data_exportable,
    ),
    CharterRule(
        id="no_rival_harvest",
        title="No rival harvest",
        inversion="Amazon private label: data generated by users must never "
        "be used to compete against them — the operator may not be both "
        "referee and player.",
        check=lambda m: not m.uses_user_data_to_compete,
    ),
    CharterRule(
        id="no_engagement_metrics",
        title="No engagement metrics",
        inversion="Memories/streaks/bait: no streaks, like-counts, or "
        "nudge-metrics that manufacture return visits. The user invokes "
        "the feature; the feature never summons the user.",
        check=lambda m: not m.has_engagement_metrics,
    ),
    CharterRule(
        id="no_data_tithe",
        title="No data tithe",
        inversion="Data-for-free funnels: the feature's core function must "
        "work without any data leaving the machine.",
        check=lambda m: not m.requires_outbound_data,
    ),
    CharterRule(
        id="honest_labeling",
        title="Honest labeling",
        inversion="Sly generosity generally: anything called 'free' must "
        "state the real trade in plain words.",
        check=lambda m: m.labels_free_accurately,
    ),
)


# ---------------------------------------------------------------------------
# Audit
# ---------------------------------------------------------------------------


@dataclass
class AuditResult:
    manifest_name: str
    passed: bool
    failures: List[Dict[str, str]]
    passes: List[str]

    def report(self) -> str:
        lines = [
            "Generosity Charter audit: %s — %s"
            % (
                self.manifest_name,
                "PASS (%d/%d)" % (len(self.passes), len(RULES))
                if self.passed
                else "FAIL",
            )
        ]
        for f in self.failures:
            lines.append("  FAIL  %-22s %s" % (f["id"], f["title"]))
            lines.append("         inverts: %s" % f["inversion"])
        for pid in self.passes:
            lines.append("  pass  %s" % pid)
        return "\n".join(lines)


def audit(manifest: GenerosityManifest) -> AuditResult:
    """Run every charter rule against a feature manifest. Deny-open on
    errors inside a single rule (a broken check fails that rule only)."""
    failures: List[Dict[str, str]] = []
    passes: List[str] = []
    for rule in RULES:
        if rule.passes(manifest):
            passes.append(rule.id)
        else:
            failures.append(
                {"id": rule.id, "title": rule.title, "inversion": rule.inversion}
            )
    return AuditResult(
        manifest_name=manifest.name,
        passed=not failures,
        failures=failures,
        passes=passes,
    )


def audit_giants_showcase() -> Dict[str, AuditResult]:
    """The four hunt finds, audited as manifests — the charter eating its
    own source material. All four must FAIL, or the rules are toothless."""
    showcases = {
        "free-basics": GenerosityManifest(
            name="Free Basics",
            has_toll_road=True,
            has_gatekeeper_curation=True,
            curation_criteria_disclosed=False,
            curation_criteria_editable=False,
            labels_free_accurately=False,
        ),
        "privacy-sandbox": GenerosityManifest(
            name="Privacy Sandbox",
            claims_privacy=True,
            privacy_verifiable_locally=False,
        ),
        "x-api": GenerosityManifest(
            name="X API",
            reserves_revoke_rights=True,
            data_exportable=False,
            has_toll_road=True,
        ),
        "amazon-marketplace": GenerosityManifest(
            name="Amazon Marketplace",
            uses_user_data_to_compete=True,
            has_gatekeeper_curation=True,
            curation_criteria_editable=False,
        ),
    }
    return {k: audit(v) for k, v in showcases.items()}
