"""The universal Operator contract: one interface, every operator.

Every operator — LEVI-native minds, other SI/AI operators, and Xi
nano-bit operators — is built the same way behind this contract, so
any operator is interchangeable with any other in any seat/role.
Swapping operators is a config change, never a code change.

Stdlib only. No torch, no numpy, no network.
"""

from .contract import (
    AI,
    FINISH_REASONS,
    FOREIGN_INJECTION_PATTERNS,
    FORBIDDEN_FOREIGN_TOOLS,
    FORBIDDEN_XI_TOOLS,
    KINDS,
    NATIVE,
    NATIVE_IDENTITY_PATTERNS,
    SI,
    XI,
    XI_INJECTION_PATTERNS,
    Operator,
    OperatorCapabilities,
    OperatorContractError,
    OperatorHealth,
    OperatorMessage,
    OperatorResult,
    OperatorStreamChunk,
    OperatorToolCall,
    claims_native_identity,
    screen_foreign_text,
    screen_xi_text,
    validate_operator,
)
from .registry import (
    DEFAULT_SEAT_MAP,
    HIGH_STAKES_TOOLS,
    KNOWN_SEATS,
    TWIN_MODES,
    OperatorRegistry,
    OperatorSession,
    TwinPair,
    assess_stakes,
    default_registry,
    escalate,
    register_builtin_operators,
    resolve_for_seat,
    resolve_for_task,
    resolve_twin,
    scoped_step,
    tier_operator,
)
from .twins import (
    FORCED_BANNER,
    HIGH_STAKES_BANNER,
    TwinArrival,
    TwinTurnResult,
    record_pick,
    run_twin_turn,
)

__all__ = [
    "AI",
    "FINISH_REASONS",
    "FOREIGN_INJECTION_PATTERNS",
    "FORBIDDEN_FOREIGN_TOOLS",
    "FORBIDDEN_XI_TOOLS",
    "FORCED_BANNER",
    "HIGH_STAKES_BANNER",
    "KINDS",
    "NATIVE",
    "NATIVE_IDENTITY_PATTERNS",
    "SI",
    "XI",
    "XI_INJECTION_PATTERNS",
    "DEFAULT_SEAT_MAP",
    "HIGH_STAKES_TOOLS",
    "KNOWN_SEATS",
    "TWIN_MODES",
    "Operator",
    "OperatorCapabilities",
    "OperatorContractError",
    "OperatorHealth",
    "OperatorMessage",
    "OperatorRegistry",
    "OperatorResult",
    "OperatorSession",
    "OperatorStreamChunk",
    "OperatorToolCall",
    "TwinPair",
    "TwinArrival",
    "TwinTurnResult",
    "assess_stakes",
    "claims_native_identity",
    "default_registry",
    "escalate",
    "record_pick",
    "register_builtin_operators",
    "resolve_for_seat",
    "resolve_for_task",
    "resolve_twin",
    "run_twin_turn",
    "scoped_step",
    "screen_foreign_text",
    "screen_xi_text",
    "tier_operator",
    "validate_operator",
]
