"""
LEVI cybersecurity skill pack — 100 original skills.

PROVENANCE (read before redistributing):
  Every playbook under core/levi/skill/playbooks/cyber/ is an ORIGINAL work
  authored for LEVI. Topic coverage is inspired by the public topic list of
  https://github.com/mukul975/Anthropic-Cybersecurity-Skills (100 skills);
  no content was copied, read, or derived from that repository's files —
  writers worked from topic names only. Topics and techniques are not
  copyrightable; the expression here is LEVI's own and is proprietary.
  Attack-technique topics are written with a defensive blue-team lens
  (detection / analysis / hardening), never as attack how-tos.

ID scheme:  cyber_<slug with hyphens replaced by underscores>
  e.g. slug "analyzing-dns-logs-for-exfiltration"
       -> id "cyber_analyzing_dns_logs_for_exfiltration"

Risk policy: read-only analysis playbooks are INFO/LOW. Anything that
acquires evidence images or touches live systems is MODERATE with
requires_confirmation=True.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from levi.skill.registry import Skill, SkillRisk

PLAYBOOK_DIR = Path(__file__).parent / "playbooks" / "cyber"


def _playbook_handler(slug: str):
    """Generic handler: returns the playbook markdown for a cyber skill."""

    def _handler(args: Optional[Dict] = None) -> str:
        target = PLAYBOOK_DIR / f"{slug}.md"
        try:
            return target.read_text(encoding="utf-8")
        except OSError as exc:
            return f"cyber skill playbook unavailable: {exc}"

    return _handler


def _cyber(
    slug: str,
    name: str,
    description: str,
    risk: SkillRisk = SkillRisk.LOW,
    permissions: Optional[List[str]] = None,
    requires_confirmation: bool = False,
    tags: Optional[List[str]] = None,
) -> Skill:
    return Skill(
        id="cyber_" + slug.replace("-", "_"),
        name=name,
        description=description,
        category="cybersecurity",
        risk_level=risk,
        permissions=list(permissions or []),
        requires_confirmation=requires_confirmation,
        tags=list(tags or []),
        version="1.0.0",
        handler=_playbook_handler(slug),
    )


MOD = SkillRisk.MODERATE
CYBER_SKILLS: List[Skill] = [
    _cyber("abusing-dpapi-for-credential-access",
           "Detecting DPAPI Abuse for Credential Access",
           "Detect and investigate Windows DPAPI abuse for credential theft: artifact locations, event-log signals, and hardening.",
           tags=["identity", "windows", "forensics"]),
    _cyber("abusing-shadow-credentials-for-privesc",
           "Detecting Shadow Credential Abuse for Privilege Escalation",
           "Detect shadow-credential persistence in Active Directory: msDS-KeyCredentialLink anomalies and remediation.",
           tags=["identity", "active-directory"]),
    _cyber("achieving-cmmc-level-2-compliance",
           "Achieving CMMC Level 2 Compliance",
           "Roadmap for CMMC Level 2: 110 practices across 14 domains, scoping, POA&M, and assessment readiness.",
           risk=SkillRisk.INFO, tags=["compliance"]),
    _cyber("acquiring-disk-image-with-dd-and-dcfldd",
           "Acquiring Disk Images with dd and dcfldd",
           "Forensically sound disk imaging with dd/dcfldd: write-blocking, hashing, and chain of custody.",
           risk=MOD, permissions=["evidence.acquire"], requires_confirmation=True,
           tags=["forensics"]),
    _cyber("analyzing-active-directory-acl-abuse",
           "Analyzing Active Directory ACL Abuse",
           "Hunt dangerous AD ACLs and attack paths: BloodHound-style analysis and remediation priority.",
           tags=["identity", "active-directory"]),
    _cyber("analyzing-android-malware-with-apktool",
           "Analyzing Android Malware with Apktool",
           "Reverse Android APKs with apktool: manifest, smali, and resource triage in an isolated lab.",
           tags=["malware-analysis", "mobile"]),
    _cyber("analyzing-api-gateway-access-logs",
           "Analyzing API Gateway Access Logs",
           "Detect abuse in API gateway logs: auth failures, scraping, injection probes, and rate anomalies.",
           tags=["network", "cloud"]),
    _cyber("analyzing-apt-group-with-mitre-navigator",
           "Analyzing APT Groups with MITRE Navigator",
           "Profile APT groups with MITRE ATT&CK Navigator: technique overlays and gap analysis.",
           tags=["threat-intel"]),
    _cyber("analyzing-azure-activity-logs-for-threats",
           "Analyzing Azure Activity Logs for Threats",
           "Hunt threats in Azure Activity logs: control-plane abuse, policy changes, and anomalous principals.",
           tags=["cloud", "siem"]),
    _cyber("analyzing-bootkit-and-rootkit-samples",
           "Analyzing Bootkit and Rootkit Samples",
           "Analyze bootkit/rootkit samples safely: boot-chain artifacts and persistence indicators.",
           tags=["malware-analysis", "forensics"]),
    _cyber("analyzing-browser-forensics-with-hindsight",
           "Analyzing Browser Forensics with Hindsight",
           "Extract Chrome history, downloads, and session artifacts with Hindsight.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-campaign-attribution-evidence",
           "Analyzing Campaign Attribution Evidence",
           "Weigh attribution evidence for intrusion campaigns: confidence levels and analytic pitfalls.",
           risk=SkillRisk.INFO, tags=["threat-intel"]),
    _cyber("analyzing-certificate-transparency-for-phishing",
           "Analyzing Certificate Transparency Logs for Phishing",
           "Hunt phishing infrastructure in CT logs: lookalike domains and suspicious issuers.",
           tags=["threat-intel", "network"]),
    _cyber("analyzing-cloud-storage-access-patterns",
           "Analyzing Cloud Storage Access Patterns",
           "Detect anomalous cloud storage access: exfiltration-shaped reads and anonymous exposure.",
           tags=["cloud"]),
    _cyber("analyzing-cobalt-strike-beacon-configuration",
           "Detecting Cobalt Strike Beacon Configurations",
           "Detect and dissect Cobalt Strike beacons: config extraction and network signatures.",
           tags=["network", "threat-intel"]),
    _cyber("analyzing-cobaltstrike-malleable-c2-profiles",
           "Detecting Cobalt Strike Malleable C2 Profiles",
           "Fingerprint malleable C2 profiles from traffic: JA3, headers, and URI patterns.",
           tags=["network", "threat-intel"]),
    _cyber("analyzing-command-and-control-communication",
           "Analyzing Command-and-Control Communication",
           "Identify C2 channels: beaconing, tunneling, and covert-channel indicators.",
           tags=["network", "threat-intel"]),
    _cyber("analyzing-cyber-kill-chain",
           "Applying the Cyber Kill Chain",
           "Map intrusions to kill-chain phases to find detection gaps and disruption points.",
           risk=SkillRisk.INFO, tags=["threat-intel"]),
    _cyber("analyzing-disk-image-with-autopsy",
           "Analyzing Disk Images with Autopsy",
           "Examine disk images with Autopsy: timeline, keyword search, and artifact modules.",
           tags=["forensics"]),
    _cyber("analyzing-dns-logs-for-exfiltration",
           "Analyzing DNS Logs for Exfiltration",
           "Detect DNS tunneling and exfiltration: entropy, query volume, and rare record types.",
           tags=["network"]),
    _cyber("analyzing-docker-container-forensics",
           "Analyzing Docker Container Forensics",
           "Forensics for compromised containers: layer diffs, exec history, and runtime artifacts.",
           tags=["forensics", "cloud"]),
    _cyber("analyzing-email-headers-for-phishing-investigation",
           "Analyzing Email Headers for Phishing Investigations",
           "Trace phishing email origins: authentication results, received chains, and header anomalies.",
           tags=["email", "threat-intel"]),
    _cyber("analyzing-ethereum-smart-contract-vulnerabilities",
           "Analyzing Ethereum Smart Contract Vulnerabilities",
           "Find common smart-contract flaws: reentrancy, access control, and oracle issues.",
           tags=["blockchain"]),
    _cyber("analyzing-golang-malware-with-ghidra",
           "Analyzing Go Malware with Ghidra",
           "Reverse Go binaries in Ghidra: runtime recovery, string tables, and package structure.",
           tags=["malware-analysis"]),
    _cyber("analyzing-heap-spray-exploitation",
           "Detecting Heap Spray Exploitation",
           "Detect heap-spray exploitation: allocation patterns, crash triage, and mitigations.",
           tags=["malware-analysis"]),
    _cyber("analyzing-indicators-of-compromise",
           "Analyzing Indicators of Compromise",
           "Build and validate IOC sets: collection, deduplication, and confidence scoring.",
           tags=["threat-intel"]),
    _cyber("analyzing-ios-app-security-with-objection",
           "Analyzing iOS App Security with Objection",
           "Dynamic iOS analysis with Objection: SSL-pinning tests and runtime inspection.",
           tags=["malware-analysis", "mobile"]),
    _cyber("analyzing-kubernetes-audit-logs",
           "Analyzing Kubernetes Audit Logs",
           "Hunt cluster intrusions in the Kubernetes audit log: anomalous verbs and service accounts.",
           tags=["kubernetes"]),
    _cyber("analyzing-linux-audit-logs-for-intrusion",
           "Analyzing Linux Audit Logs for Intrusion",
           "Detect Linux intrusions via auditd: execve anomalies, privilege use, and persistence.",
           tags=["linux", "siem"]),
    _cyber("analyzing-linux-elf-malware",
           "Analyzing Linux ELF Malware",
           "Triage Linux ELF malware: headers, sections, strings, and sandboxed dynamic behavior.",
           tags=["malware-analysis", "linux"]),
    _cyber("analyzing-linux-kernel-rootkits",
           "Analyzing Linux Kernel Rootkits",
           "Detect kernel-mode rootkits: syscall-table hooks, module hiding, and memory forensics.",
           tags=["malware-analysis", "linux"]),
    _cyber("analyzing-linux-system-artifacts",
           "Analyzing Linux System Artifacts",
           "Collect Linux post-compromise artifacts: journals, auth logs, cron, and shell history.",
           tags=["forensics", "linux"]),
    _cyber("analyzing-lnk-file-and-jump-list-artifacts",
           "Analyzing LNK File and Jump List Artifacts",
           "Reconstruct execution history from LNK files and Jump Lists.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-macro-malware-in-office-documents",
           "Analyzing Macro Malware in Office Documents",
           "Extract and analyze malicious VBA macros from Office documents safely.",
           tags=["malware-analysis"]),
    _cyber("analyzing-malicious-pdf-with-peepdf",
           "Analyzing Malicious PDFs with peepdf",
           "Dissect malicious PDFs with peepdf: objects, streams, and embedded exploits.",
           tags=["malware-analysis"]),
    _cyber("analyzing-malicious-url-with-urlscan",
           "Analyzing Malicious URLs with urlscan.io",
           "Detonate suspicious URLs with urlscan.io: DOM, network, and verdict analysis.",
           permissions=["network.read"], tags=["threat-intel", "network"]),
    _cyber("analyzing-malware-behavior-with-cuckoo-sandbox",
           "Analyzing Malware Behavior with Cuckoo Sandbox",
           "Automated dynamic analysis with Cuckoo: behavioral signatures and report triage.",
           tags=["malware-analysis"]),
    _cyber("analyzing-malware-family-relationships-with-malpedia",
           "Analyzing Malware Family Relationships with Malpedia",
           "Attribute samples to families with Malpedia: YARA, configs, and code overlap.",
           tags=["malware-analysis", "threat-intel"]),
    _cyber("analyzing-malware-persistence-with-autoruns",
           "Analyzing Malware Persistence with Autoruns",
           "Enumerate Windows persistence with Autoruns and spot malicious entries.",
           tags=["malware-analysis", "windows"]),
    _cyber("analyzing-malware-sandbox-evasion-techniques",
           "Analyzing Malware Sandbox Evasion Techniques",
           "Recognize sandbox evasion: sleeps, VM checks, and human-interaction gates.",
           tags=["malware-analysis"]),
    _cyber("analyzing-memory-dumps-with-volatility",
           "Analyzing Memory Dumps with Volatility",
           "Memory forensics with Volatility: processes, network, and injection artifacts.",
           tags=["forensics", "malware-analysis"]),
    _cyber("analyzing-memory-forensics-with-lime-and-volatility",
           "Analyzing Memory Forensics with LiME and Volatility",
           "Acquire Linux memory with LiME and analyze it with Volatility.",
           tags=["forensics", "linux"]),
    _cyber("analyzing-mft-for-deleted-file-recovery",
           "Analyzing the MFT for Deleted File Recovery",
           "Recover deleted files via $MFT analysis: resident vs non-resident data runs.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-network-covert-channels-in-malware",
           "Analyzing Network Covert Channels in Malware",
           "Detect covert channels: DNS/ICMP tunneling and protocol misuse.",
           tags=["network", "malware-analysis"]),
    _cyber("analyzing-network-flow-data-with-netflow",
           "Analyzing Network Flow Data with NetFlow",
           "Hunt lateral movement and exfiltration in NetFlow/IPFIX records.",
           tags=["network"]),
    _cyber("analyzing-network-packets-with-scapy",
           "Analyzing Network Packets with Scapy",
           "Packet-level analysis with Scapy: dissect, filter, and reassemble.",
           tags=["network"]),
    _cyber("analyzing-network-traffic-for-incidents",
           "Analyzing Network Traffic for Incidents",
           "Incident-driven traffic analysis: scoping, timeline, and C2 confirmation.",
           tags=["network"]),
    _cyber("analyzing-network-traffic-of-malware",
           "Analyzing Network Traffic of Malware",
           "Profile malware network behavior: DNS, HTTP, and encrypted channels in a lab.",
           tags=["network", "malware-analysis"]),
    _cyber("analyzing-network-traffic-with-wireshark",
           "Analyzing Network Traffic with Wireshark",
           "Deep packet inspection with Wireshark: filters, streams, and expert analysis.",
           tags=["network"]),
    _cyber("analyzing-office365-audit-logs-for-compromise",
           "Analyzing Office 365 Audit Logs for Compromise",
           "Detect M365 compromise: impossible travel, inbox rules, and consent grants.",
           tags=["cloud", "siem"]),
    _cyber("analyzing-outlook-pst-for-email-forensics",
           "Analyzing Outlook PST Files for Email Forensics",
           "Extract email evidence from PST files: messages, attachments, and metadata.",
           tags=["forensics", "email"]),
    _cyber("analyzing-packed-malware-with-upx-unpacker",
           "Analyzing Packed Malware with UPX",
           "Unpack UPX-packed malware and verify the unpacked payload.",
           tags=["malware-analysis"]),
    _cyber("analyzing-pdf-malware-with-pdfid",
           "Analyzing PDF Malware with pdfid",
           "Triage suspicious PDFs fast with pdfid keyword statistics.",
           tags=["malware-analysis"]),
    _cyber("analyzing-persistence-mechanisms-in-linux",
           "Analyzing Persistence Mechanisms in Linux",
           "Enumerate Linux persistence: systemd, cron, rc files, and kernel modules.",
           tags=["linux", "malware-analysis"]),
    _cyber("analyzing-powershell-empire-artifacts",
           "Analyzing PowerShell Empire Artifacts",
           "Detect Empire framework residue: stagers, modules, and logging artifacts.",
           tags=["malware-analysis", "windows"]),
    _cyber("analyzing-powershell-script-block-logging",
           "Analyzing PowerShell Script Block Logging",
           "Hunt obfuscated PowerShell via Script Block Logging (Event 4104).",
           tags=["windows", "siem"]),
    _cyber("analyzing-prefetch-files-for-execution-history",
           "Analyzing Prefetch Files for Execution History",
           "Reconstruct program execution from Windows Prefetch files.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-ransomware-encryption-mechanisms",
           "Analyzing Ransomware Encryption Mechanisms",
           "Understand ransomware crypto: key management, speed, and recovery options.",
           tags=["ransomware", "malware-analysis"]),
    _cyber("analyzing-ransomware-leak-site-intelligence",
           "Analyzing Ransomware Leak Site Intelligence",
           "Monitor ransomware leak sites safely: victim tracking and OPSEC.",
           permissions=["network.read"], tags=["ransomware", "threat-intel"]),
    _cyber("analyzing-ransomware-network-indicators",
           "Analyzing Ransomware Network Indicators",
           "Block ransomware at the network layer: pre-encryption indicators and C2.",
           tags=["ransomware", "network"]),
    _cyber("analyzing-ransomware-payment-wallets",
           "Analyzing Ransomware Payment Wallets",
           "Trace ransomware payments on-chain: clustering and exchange touchpoints.",
           permissions=["network.read"], tags=["ransomware", "blockchain"]),
    _cyber("analyzing-sbom-for-supply-chain-vulnerabilities",
           "Analyzing SBOMs for Supply Chain Vulnerabilities",
           "Turn SBOMs into findings: vulnerable components and policy gates.",
           tags=["supply-chain"]),
    _cyber("analyzing-security-logs-with-splunk",
           "Analyzing Security Logs with Splunk",
           "Security analytics in Splunk: SPL patterns for common attack classes.",
           tags=["siem"]),
    _cyber("analyzing-slack-space-and-file-system-artifacts",
           "Analyzing Slack Space and File System Artifacts",
           "Recover slack-space remnants and file-system artifacts.",
           tags=["forensics"]),
    _cyber("analyzing-supply-chain-malware-artifacts",
           "Analyzing Supply Chain Malware Artifacts",
           "Investigate compromised dependencies and build artifacts.",
           tags=["supply-chain", "malware-analysis"]),
    _cyber("analyzing-threat-actor-ttps-with-mitre-attack",
           "Analyzing Threat Actor TTPs with MITRE ATT&CK",
           "Map adversary behavior to ATT&CK: technique mapping and coverage gaps.",
           tags=["threat-intel"]),
    _cyber("analyzing-threat-actor-ttps-with-mitre-navigator",
           "Analyzing Threat Actor TTPs with MITRE Navigator",
           "Visualize TTP overlap across actors with ATT&CK Navigator layers.",
           tags=["threat-intel"]),
    _cyber("analyzing-threat-intelligence-feeds",
           "Analyzing Threat Intelligence Feeds",
           "Evaluate and operationalize threat feeds: scoring, aging, and false positives.",
           permissions=["network.read"], tags=["threat-intel"]),
    _cyber("analyzing-threat-landscape-with-misp",
           "Analyzing the Threat Landscape with MISP",
           "Correlate threats in MISP: galaxies, sightings, and event triage.",
           tags=["threat-intel"]),
    _cyber("analyzing-tls-certificate-transparency-logs",
           "Analyzing TLS Certificate Transparency Logs",
           "Audit CT logs for rogue and lookalike certificates.",
           permissions=["network.read"], tags=["threat-intel", "network"]),
    _cyber("analyzing-typosquatting-domains-with-dnstwist",
           "Analyzing Typosquatting Domains with dnstwist",
           "Find typosquat domains with dnstwist: permutations and registration checks.",
           permissions=["network.read"], tags=["threat-intel"]),
    _cyber("analyzing-uefi-bootkit-persistence",
           "Analyzing UEFI Bootkit Persistence",
           "Detect UEFI bootkit persistence: SPI flash, boot variables, and Secure Boot.",
           tags=["firmware", "malware-analysis"]),
    _cyber("analyzing-usb-device-connection-history",
           "Analyzing USB Device Connection History",
           "Reconstruct USB connections: registry, logs, and setupapi artifacts.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-web-server-logs-for-intrusion",
           "Analyzing Web Server Logs for Intrusion",
           "Detect web intrusions: traversal, injection, and webshell indicators.",
           tags=["network", "siem"]),
    _cyber("analyzing-windows-amcache-artifacts",
           "Analyzing Windows Amcache Artifacts",
           "Extract program execution evidence from Amcache.hve.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-windows-event-logs-in-splunk",
           "Analyzing Windows Event Logs in Splunk",
           "Windows event analytics in Splunk: high-value Event IDs and detection SPL.",
           tags=["windows", "siem"]),
    _cyber("analyzing-windows-lnk-files-for-artifacts",
           "Analyzing Windows LNK Files for Artifacts",
           "Parse Windows shortcut files for execution and exfiltration evidence.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-windows-prefetch-with-python",
           "Analyzing Windows Prefetch with Python",
           "Parse Prefetch files programmatically in Python for timeline building.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-windows-registry-for-artifacts",
           "Analyzing the Windows Registry for Artifacts",
           "Systematic registry forensics: hives, keys, and timeline correlation.",
           tags=["forensics", "windows"]),
    _cyber("analyzing-windows-shellbag-artifacts",
           "Analyzing Windows Shellbag Artifacts",
           "Reconstruct folder access history from Shellbags.",
           tags=["forensics", "windows"]),
    _cyber("assessing-vector-and-embedding-weaknesses",
           "Assessing Vector and Embedding Weaknesses",
           "Assess AI embedding/vector-store risks: poisoning, leakage, and inversion.",
           tags=["ai-security"]),
    _cyber("attacking-entra-id-with-roadtools",
           "Detecting Entra ID Attacks Using Roadtools Techniques",
           "Detect Roadtools-style Entra ID tradecraft: token abuse and PRT signals.",
           tags=["identity", "cloud"]),
    _cyber("attacking-oauth-with-device-code-phishing",
           "Detecting OAuth Device Code Phishing",
           "Detect device-code phishing: flow anomalies and Conditional Access hardening.",
           tags=["identity"]),
    _cyber("auditing-aws-s3-bucket-permissions",
           "Auditing AWS S3 Bucket Permissions",
           "Audit S3 buckets for public exposure and misconfigured policies.",
           risk=MOD, permissions=["cloud.read"], requires_confirmation=True,
           tags=["cloud"]),
    _cyber("auditing-azure-active-directory-configuration",
           "Auditing Azure Active Directory Configuration",
           "Audit Azure AD/Entra ID configuration: legacy auth, admin roles, and app consents.",
           risk=MOD, permissions=["cloud.read"], requires_confirmation=True,
           tags=["cloud", "identity"]),
    _cyber("auditing-cloud-with-cis-benchmarks",
           "Auditing Cloud Environments with CIS Benchmarks",
           "Assess cloud posture against CIS Benchmarks: scoring and remediation.",
           risk=MOD, permissions=["cloud.read"], requires_confirmation=True,
           tags=["cloud", "compliance"]),
    _cyber("auditing-entra-id-with-aadinternals",
           "Auditing Entra ID with AADInternals",
           "Deep Entra ID assessment with AADInternals: recon, misconfigurations, and drift.",
           risk=MOD, permissions=["cloud.read"], requires_confirmation=True,
           tags=["identity", "cloud"]),
    _cyber("auditing-foundry-smart-contract-security",
           "Auditing Smart Contract Security with Foundry",
           "Security testing with Foundry: fuzz, invariant tests, and Slither triage.",
           tags=["blockchain"]),
    _cyber("auditing-gcp-iam-permissions",
           "Auditing GCP IAM Permissions",
           "Audit GCP IAM: over-privileged bindings and primitive-role usage.",
           risk=MOD, permissions=["cloud.read"], requires_confirmation=True,
           tags=["cloud"]),
    _cyber("auditing-kubernetes-cluster-rbac",
           "Auditing Kubernetes Cluster RBAC",
           "Audit Kubernetes RBAC: cluster-admin bindings and wildcard verbs.",
           risk=MOD, permissions=["k8s.read"], requires_confirmation=True,
           tags=["kubernetes"]),
    _cyber("auditing-kubernetes-rbac-privilege-escalation",
           "Auditing Kubernetes RBAC for Privilege Escalation Paths",
           "Map RBAC privilege-escalation paths: role aggregation and node proxy abuse.",
           risk=MOD, permissions=["k8s.read"], requires_confirmation=True,
           tags=["kubernetes"]),
    _cyber("auditing-mcp-servers-for-tool-poisoning",
           "Auditing MCP Servers for Tool Poisoning",
           "Audit Model Context Protocol servers: tool schemas, prompt injection, and poisoning.",
           tags=["ai-security"]),
    _cyber("auditing-terraform-infrastructure-for-security",
           "Auditing Terraform Infrastructure for Security",
           "Static security review of Terraform: tfsec/checkov and state hygiene.",
           tags=["cloud", "supply-chain"]),
    _cyber("auditing-tls-certificate-transparency-logs",
           "Auditing TLS Certificate Transparency Logs",
           "Continuous CT monitoring for your domains: alerting on unauthorized issuance.",
           permissions=["network.read"], tags=["threat-intel", "network"]),
    _cyber("auditing-uefi-firmware-with-chipsec",
           "Auditing UEFI Firmware with CHIPSEC",
           "Audit platform firmware with CHIPSEC: SPI protections and Secure Boot state.",
           risk=MOD, permissions=["system.read"], requires_confirmation=True,
           tags=["firmware"]),
    _cyber("automating-ioc-enrichment",
           "Automating IOC Enrichment",
           "Build IOC enrichment pipelines: VT/OTX lookups, scoring, and SIEM push.",
           permissions=["network.read"], tags=["threat-intel"]),
    _cyber("benchmarking-kubernetes-with-kube-bench",
           "Benchmarking Kubernetes with kube-bench",
           "Run CIS Kubernetes Benchmarks with kube-bench: scoring and remediation.",
           risk=MOD, permissions=["k8s.read"], requires_confirmation=True,
           tags=["kubernetes", "compliance"]),
    _cyber("building-adversary-infrastructure-tracking-system",
           "Building an Adversary Infrastructure Tracking System",
           "Track adversary infrastructure: passive DNS, certificates, and pivoting.",
           permissions=["network.read"], tags=["threat-intel"]),
    _cyber("building-attack-pattern-library-from-cti-reports",
           "Building an Attack Pattern Library from CTI Reports",
           "Distill CTI reports into reusable ATT&CK-mapped detection patterns.",
           tags=["threat-intel"]),
    _cyber("building-automated-malware-submission-pipeline",
           "Building an Automated Malware Submission Pipeline",
           "Automate sandbox submissions: triage, API submission, and verdict ingestion.",
           risk=MOD, permissions=["network.write"], requires_confirmation=True,
           tags=["malware-analysis"]),
]
