"""Alpha revival: the no-code compiler's generator registry, LEVI-native.

Omega's Alpha compiled Echo blueprints into working products through a
registry of named generators (webpage, backend, CLI, MCP server, ...).
This module is that mechanism from scratch: register a generator per
product type, then compile any validated blueprint into real scaffold
files — returned as ``{path: content}`` so the caller decides where
they land.

Public surface:

- ``Generator`` — ``name``, ``title``, ``description``,
  ``product_types`` and ``generate(blueprint) -> Dict[str, str]``.
- ``register(generator)`` / ``get(name)`` / ``registered()``.
- ``generators_for(blueprint)`` — generators matching the blueprint's
  product types, in blueprint order.
- ``compile_blueprint(blueprint)`` — validate, then run every matching
  generator; returns ``{"ok", "files", "errors", "blueprint"}``.

Six LEVI-native generators ship built in: ``webpage``, ``cli``,
``api`` (FastAPI), ``mcp_server``, ``automation``, ``skill``. Generated code
is honest about its provenance (header comment) and its dependencies.

Defensive notes:

- ``compile_blueprint`` validates first via ``blueprint.validate_blueprint``
  and refuses invalid input instead of generating garbage.
- A failing generator never aborts the compile: its error is recorded in
  ``errors`` and the remaining generators still run.
- Duplicate registration is a ``ValueError`` — silent overwrites hide
  bugs; rename or unregister explicitly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List

from .blueprint import ORIGIN as BLUEPRINT_ORIGIN
from .blueprint import validate_blueprint

ORIGIN = "levi-revival-omega/alpha"

GenerateFn = Callable[[Dict[str, Any]], Dict[str, str]]


@dataclass
class Generator:
    name: str
    title: str
    description: str
    product_types: List[str]
    generate: GenerateFn = field(repr=False)


_REGISTRY: Dict[str, Generator] = {}


def register(generator: Generator) -> Generator:
    if not generator.name or not isinstance(generator.name, str):
        raise ValueError("generator must have a non-empty string name")
    if generator.name in _REGISTRY:
        raise ValueError(f"generator already registered: {generator.name!r}")
    _REGISTRY[generator.name] = generator
    return generator


def unregister(name: str) -> None:
    if name not in _REGISTRY:
        raise ValueError(f"unknown generator: {name!r}")
    del _REGISTRY[name]


def get(name: str) -> Generator:
    try:
        return _REGISTRY[name]
    except KeyError:
        raise ValueError(f"unknown generator: {name!r}") from None


def registered() -> List[str]:
    return sorted(_REGISTRY)


def generators_for(blueprint: Dict[str, Any]) -> List[Generator]:
    wanted = blueprint.get("product_types", []) if isinstance(blueprint, dict) else []
    found: List[Generator] = []
    for ptype in wanted:
        for gen in _REGISTRY.values():
            if ptype in gen.product_types and gen not in found:
                found.append(gen)
    return found


def compile_blueprint(blueprint: Dict[str, Any]) -> Dict[str, Any]:
    """Validate a blueprint, then run every matching generator."""
    check = validate_blueprint(blueprint)
    if not check["ok"]:
        return {
            "ok": False,
            "files": {},
            "errors": [f"invalid blueprint: {e}" for e in check["errors"]],
            "blueprint": blueprint if isinstance(blueprint, dict) else {},
        }
    files: Dict[str, str] = {}
    errors: List[str] = []
    for gen in generators_for(blueprint):
        try:
            produced = gen.generate(blueprint)
        except Exception as exc:  # noqa: BLE001 - recorded, not raised
            errors.append(f"{gen.name}: {exc}")
            continue
        if not isinstance(produced, dict):
            errors.append(
                f"{gen.name}: generator must return dict, got {type(produced).__name__}"
            )
            continue
        for path, content in produced.items():
            if path in files:
                errors.append(f"{gen.name}: path collision on {path!r}")
                continue
            files[path] = content
    return {"ok": not errors, "files": files, "errors": errors, "blueprint": blueprint}


def _header(blueprint: Dict[str, Any], kind: str) -> str:
    return (
        f"Generated by LEVI revival/omega ({BLUEPRINT_ORIGIN} -> {ORIGIN})\n"
        f"kind: {kind} | app: {blueprint['name']} | "
        f"prompt: {blueprint['prompt'][:60]}\n"
        "This is a scaffold: review and extend before use.\n"
    )


def _py_header(blueprint: Dict[str, Any], kind: str) -> str:
    """Header formatted as Python comments for generated .py files."""
    return "\n".join("# " + line for line in _header(blueprint, kind).splitlines())


def _gen_webpage(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    title = blueprint["title"]
    html = f"""<!DOCTYPE html>
<!-- {_header(blueprint, "webpage").replace(chr(10), chr(10) + "  ")}-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<main>
  <h1>{title}</h1>
  <p>Scaffold generated from: {blueprint["prompt"][:120]}</p>
  <div id="app"></div>
</main>
<script src="app.js"></script>
</body>
</html>
"""
    css = """/* LEVI-generated scaffold styles */
:root { color-scheme: dark; }
body { font-family: system-ui, sans-serif; margin: 2rem; background: #0b0b10; color: #e8e8ee; }
main { max-width: 42rem; margin: 0 auto; }
"""
    js = f"""// {title} — LEVI-generated scaffold
document.getElementById('app').textContent = 'Hello from {name}.';
"""
    return {f"{name}/index.html": html, f"{name}/styles.css": css, f"{name}/app.js": js}


def _gen_cli(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    module = name.replace("-", "_")
    main_py = f'''"""{blueprint["title"]} — LEVI-generated CLI scaffold (stdlib only)."""
{_py_header(blueprint, "cli")}
from __future__ import annotations

import argparse
import sys


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="{name}", description="{blueprint["title"]}")
    parser.add_argument("--version", action="store_true", help="print version and exit")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.version:
        print("{name} 0.1.0")
        return 0
    print("TODO: implement {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
    readme = f"""# {blueprint["title"]}\n\n{_header(blueprint, "cli")}\n## Run\n\n```bash\npython {module}.py --version\n```\n"""
    return {f"{name}/{module}.py": main_py, f"{name}/README.md": readme}


def _gen_api(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    module = name.replace("-", "_")
    app_py = f'''"""{blueprint["title"]} — LEVI-generated FastAPI scaffold."""
{_py_header(blueprint, "api")}
# Requires: pip install fastapi uvicorn
from fastapi import FastAPI

app = FastAPI(title="{blueprint["title"]}")


@app.get("/health")
def health() -> dict:
    return {{"ok": True, "app": "{name}"}}


@app.get("/hello")
def hello(name: str = "world") -> dict:
    return {{"message": f"hello {{name}} from {name}"}}
'''
    requirements = "fastapi\nuvicorn\n"
    readme = (
        f"# {blueprint['title']}\n\n{_header(blueprint, 'api')}\n"
        "## Run\n\n```bash\npip install -r requirements.txt\n"
        f"uvicorn {module}:app --reload\n```\n"
    )
    return {
        f"{name}/{module}.py": app_py,
        f"{name}/requirements.txt": requirements,
        f"{name}/README.md": readme,
    }


def _gen_mcp_server(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    module = name.replace("-", "_")
    server_py = f'''"""{blueprint["title"]} — LEVI-generated MCP server scaffold (stdio)."""
{_py_header(blueprint, "mcp_server")}
# Requires: pip install mcp
import asyncio

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

server = Server("{name}")


@server.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="ping",
            description="Health check for the {name} MCP server.",
            inputSchema={{"type": "object", "properties": {{}}}},
        )
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict):
    if name == "ping":
        return [TextContent(type="text", text="pong from {name}")]
    raise ValueError(f"unknown tool: {{name}}")


async def main() -> None:
    async with stdio_server() as (read, write):
        await server.run(read, write, server.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
'''
    readme = (
        f"# {blueprint['title']}\n\n{_header(blueprint, 'mcp_server')}\n"
        "## Run\n\n```bash\npip install mcp\n"
        f"python {module}.py\n```\n"
    )
    return {f"{name}/{module}.py": server_py, f"{name}/README.md": readme}


def _yaml_str(text: str) -> str:
    """Make free text safe for a double-quoted YAML frontmatter scalar."""
    return re.sub(r"\s+", " ", text or "").strip().replace('"', "'")


_AUTOMATION_RUNNER_SRC = '''"""Stdlib-only runner for the declarative WORKFLOW spec above.

A rite in three movements:

1. trigger — the knock that wakes the workflow. This scaffold defaults to
   ``manual``; write a schedule note or an event name here when this rite
   earns one.
2. steps   — small named actions, performed in order.
3. receipt — a sealed record of every run: printed as JSON and appended
   to the receipt journal.

Supported step actions: ``say`` (print a line), ``write`` (write text to a
file), ``stamp`` (append one line to the journal).

Nothing here touches the network or needs a third-party package.
"""


def _utcnow() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def run_step(step, journal):
    """Perform one step; returns a small result record."""
    action = step.get("action", "say")
    if action == "say":
        print(step.get("says", step.get("name", "")))
    elif action == "write":
        path = Path(step["path"])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(step.get("text", ""), encoding="utf-8")
        print(f"wrote {path}")
    elif action == "stamp":
        journal.parent.mkdir(parents=True, exist_ok=True)
        with journal.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps({"at": _utcnow(), "step": step.get("name")}) + "\\n")
        print(f"stamped {journal}")
    else:
        raise ValueError(f"unknown step action: {action!r}")
    return {"step": step.get("name"), "action": action, "ok": True}


def run_workflow(spec, dry_run=False):
    """Wake the workflow, perform its steps, seal the receipt."""
    journal = Path(spec.get("receipt", {}).get("journal", "receipts.jsonl"))
    started = _utcnow()
    if dry_run:
        print(f"[dry run] would perform {len(spec.get('steps', []))} steps")
        return {"workflow": spec.get("name"), "dry_run": True, "ok": True}
    results = [run_step(step, journal) for step in spec.get("steps", [])]
    receipt = {
        "workflow": spec.get("name"),
        "started": started,
        "finished": _utcnow(),
        "steps": results,
        "ok": True,
    }
    journal.parent.mkdir(parents=True, exist_ok=True)
    with journal.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(receipt) + "\\n")
    return receipt


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog=WORKFLOW.get("name", "workflow"))
    parser.add_argument("--dry-run", action="store_true",
                        help="rehearse without touching anything")
    args = parser.parse_args(argv)
    receipt = run_workflow(WORKFLOW, dry_run=args.dry_run)
    print(json.dumps(receipt, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _gen_automation(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    spec = {
        "name": name,
        "title": blueprint["title"],
        "trigger": {
            "kind": "manual",
            "note": "Run `python workflow.py`. Write a schedule note or an "
            "event name here when this rite earns one.",
        },
        "steps": [
            {
                "name": "announce",
                "action": "say",
                "says": f"{blueprint['title']} begins.",
            },
            {
                "name": "leave-a-mark",
                "action": "write",
                "path": f"{name}.ran.txt",
                "text": f"{blueprint['title']} ran.\n",
            },
            {"name": "remember", "action": "stamp"},
        ],
        "receipt": {"journal": f"{name}.receipts.jsonl"},
    }
    workflow_py = (
        f'"""{blueprint["title"]} — a small synthetic rite LEVI can wake and perform '
        '(stdlib only)."""\n'
        f"{_py_header(blueprint, 'automation')}\n"
        "from __future__ import annotations\n\n"
        "import argparse\n"
        "import datetime as _dt\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n\n\n"
        f"WORKFLOW = {spec!r}\n\n\n" + _AUTOMATION_RUNNER_SRC
    )
    readme = (
        f"# {blueprint['title']}\n\n{_header(blueprint, 'automation')}\n"
        "An automation rite: a small declarative workflow LEVI can wake and "
        "perform — synthetic, local, no third-party services.\n\n"
        "## The shape\n\n"
        "- **trigger** — the knock that starts it (manual, a schedule note, "
        "or an event name)\n"
        "- **steps** — small named actions, performed in order "
        "(`say`, `write`, `stamp`)\n"
        "- **receipt** — a sealed JSON record of every run, appended to the "
        "journal\n\n"
        "## Run\n\n"
        "```bash\n"
        "python workflow.py            # perform the rite\n"
        "python workflow.py --dry-run  # rehearse without touching anything\n"
        "```\n"
    )
    return {f"{name}/workflow.py": workflow_py, f"{name}/README.md": readme}


def _gen_skill(blueprint: Dict[str, Any]) -> Dict[str, str]:
    name = blueprint["name"]
    title = blueprint["title"]
    skill_md = f'''---
skill_id: "{_yaml_str(name)}"
name: "{_yaml_str(title)}"
description: "{_yaml_str(blueprint["prompt"][:140])}"
version: "0.1.0"
risk: "info"
permissions: []
requires_confirmation: false
tags: ["generated", "revival"]
source: "levi-revival-omega/alpha"
---
# {title}

## Purpose

{_yaml_str(blueprint["prompt"][:200])}

Scaffolded by LEVI's Alpha compiler from a plain-language request. Fill in the
steps below with the real procedure, then wire `skill.py` to make the skill
executable.

## When to use

- When the request matches the purpose above.
- When a small, repeatable capability is needed instead of a one-off answer.

## Steps

1. Parse the request arguments (`python skill.py --help`).
2. Do the work locally — local-first, stdlib only, no paid APIs.
3. Return a short human-readable summary.

## Output contract

- On success: one-line summary plus the result payload.
- On failure: a clear reason and what to do next.

## Operating rules

1. Never collect or store credentials (keys, secrets, passwords, tokens).
2. Never send user data off-machine; local-first always.
3. Defensive only — detection, analysis, hardening. Nothing offensive.

## Honesty notes

- Risk `info` is a starter guess — verify before real use.
- A skill that cannot explain itself in one line is not ready.
'''
    skill_py = (
        '''"""{TITLE} — LEVI skill scaffold (stdlib only)."""
{PY_HEADER}
from __future__ import annotations

import argparse
import json
import sys

SKILL_ID = "{SKILL_ID}"


def run_skill(task: str) -> dict:
    """Do the skill's work locally and return a result payload.

    Local-first: stdlib only, no network, no credentials, no paid APIs.
    Fill in the real procedure here.
    """
    return {
        "skill": SKILL_ID,
        "task": task,
        "summary": f"TODO: implement {SKILL_ID}",
        "ok": True,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog=SKILL_ID, description="{TITLE}")
    parser.add_argument("task", nargs="?", default="",
                        help="the task for this skill")
    parser.add_argument("--json", action="store_true",
                        help="print the raw result payload")
    args = parser.parse_args(argv)
    result = run_skill(args.task)
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result["summary"])
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
'''.replace("{TITLE}", title)
        .replace("{SKILL_ID}", name)
        .replace("{PY_HEADER}", _py_header(blueprint, "skill"))
    )
    return {f"{name}/SKILL.md": skill_md, f"{name}/skill.py": skill_py}


register(
    Generator(
        name="webpage",
        title="Static webpage",
        description="Single-page site scaffold: HTML + CSS + JS.",
        product_types=["webpage"],
        generate=_gen_webpage,
    )
)
register(
    Generator(
        name="cli",
        title="Python CLI tool",
        description="argparse-based stdlib-only command-line scaffold.",
        product_types=["cli"],
        generate=_gen_cli,
    )
)
register(
    Generator(
        name="api",
        title="FastAPI backend",
        description="FastAPI app scaffold with health endpoint (needs fastapi).",
        product_types=["api"],
        generate=_gen_api,
    )
)
register(
    Generator(
        name="mcp_server",
        title="MCP server",
        description="Model Context Protocol stdio server scaffold (needs mcp).",
        product_types=["mcp_server"],
        generate=_gen_mcp_server,
    )
)
register(
    Generator(
        name="automation",
        title="Automation rite",
        description="Declarative trigger -> steps -> receipt workflow scaffold (stdlib only).",
        product_types=["automation"],
        generate=_gen_automation,
    )
)
register(
    Generator(
        name="skill",
        title="LEVI skill",
        description="LEVI skill scaffold: SKILL.md in LEVI's skill format plus an executable stdlib stub.",
        product_types=["skill"],
        generate=_gen_skill,
    )
)
