#!/usr/bin/env python3
"""Build the LEVI Boot Camp 30-day syllabus outline.

The syllabus is an OUTLINE only: per (day, track) it carries a title,
objectives, key questions, and an exercise type. Detailed lesson content
is synthesized at session time by run_session.py (research + original
LEVI-authored synthesis), so teaching compounds instead of repeating.

Usage: python3 build_syllabus.py [--out syllabus.json]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def E(title, objectives, key_questions, exercise_type):
    return {
        "title": title,
        "objectives": list(objectives),
        "key_questions": list(key_questions),
        "exercise_type": exercise_type,
    }


WEEKS = [
    {
        "week": 1,
        "days": [1, 7],
        "phase": "Foundations",
        "note": (
            "Core vocabulary and mental models. Every later lesson assumes "
            "this week's concepts; the runner reads the journal so teaching "
            "compounds instead of repeating."
        ),
    },
    {
        "week": 2,
        "days": [8, 14],
        "phase": "Intermediate Methods",
        "note": (
            "Working methods: engineering detections, tuning, hunting with "
            "structure, consuming intel, operating LEVI's subsystems for real."
        ),
    },
    {
        "week": 3,
        "days": [15, 21],
        "phase": "Advanced Application",
        "note": (
            "Harder, longer-horizon work: advanced hunts, DFIR, cross-domain "
            "orchestration, platform teardowns with investment-grade depth."
        ),
    },
    {
        "week": 4,
        "days": [22, 30],
        "phase": "Mastery + Synthesis",
        "note": (
            "Capstones, war-games, and honest self-assessment. Ends with "
            "Session 120: cross-track graduation assessment and a brain retrain."
        ),
    },
]

TRACK_A = [  # Defensive Security Analyst — defensive-only, always.
    E("The Defender's Map",
      ["Use ATT&CK as a defensive coverage map, not an attacker menu",
       "Name the D3FEND countermeasure families that pair with common techniques",
       "Run the evidence-first analyst loop: observe, hypothesize, verify"],
      ["What does ATT&CK give a defender that a technique list alone does not?",
       "How does D3FEND complement ATT&CK?",
       "What makes evidence 'first' in the analyst loop?"],
      "coverage-map"),
    E("Telemetry: What Defenders Can See",
      ["Inventory the major telemetry sources: endpoint, network, identity, cloud",
       "Explain what each source can and cannot prove",
       "Choose the right source for a given investigative question"],
      ["Which telemetry answers 'what ran on this host'?",
       "What can network telemetry prove that endpoint telemetry cannot?",
       "Why is identity telemetry the fastest-growing blind spot?"],
      "detection-sketch"),
    E("The Detection Lifecycle",
      ["Walk a detection from idea to draft to test to production to tune",
       "Define what 'production-ready' means for a detection",
       "Explain detection debt and how it accumulates"],
      ["What are the stages of the detection lifecycle?",
       "When is a detection ready for production?",
       "What is detection debt?"],
      "detection-sketch"),
    E("Sigma: Detections as Code",
      ["Read and write Sigma rule structure: logsource, detection, condition",
       "Explain why vendor-agnostic rules reduce lock-in",
       "Convert a hunting idea into a Sigma draft"],
      ["What are the three required parts of a Sigma rule?",
       "Why does a vendor-agnostic format matter?",
       "What does the condition field control?"],
      "detection-sketch"),
    E("Alert Triage Under Load",
      ["Prioritize alerts by severity, fidelity, and asset value",
       "Run a triage queue without dropping criticals",
       "Write triage notes another analyst can act on"],
      ["What three factors set triage priority?",
       "How do you avoid alert fatigue without missing real incidents?",
       "What belongs in a triage note?"],
      "triage"),
    E("Documentation That Holds Up",
      ["Write incident notes with timestamps, sources, and confidence",
       "Maintain chain of custody for digital evidence",
       "Produce a report a non-technical reader can follow"],
      ["What three things must every incident note carry?",
       "What is chain of custody and why does it matter?",
       "How do you write for non-technical readers without losing accuracy?"],
      "intel-brief"),
    E("Week 1 Review: Coverage Drill",
      ["Map the week's concepts onto defensive coverage",
       "Identify your own weakest area from the week",
       "Set week-2 learning targets"],
      ["Which week-1 concept maps to which defensive layer?",
       "Where is your coverage thinnest?",
       "What will you do differently in week 2?"],
      "coverage-map"),
    E("Detection Engineering, Deep",
      ["Design high-fidelity detections from behavior, not signatures",
       "Select log sources that maximize signal",
       "Write detection logic that survives attacker variation"],
      ["Why do behavior-based detections outlast signature-based ones?",
       "How do you choose log sources for a detection?",
       "What makes detection logic brittle?"],
      "detection-sketch"),
    E("Killing False Positives",
      ["Baseline normal before tuning anything",
       "Apply allowlisting without blinding the detection",
       "Measure precision and tune iteratively"],
      ["Why must baselining precede tuning?",
       "When does allowlisting become dangerous?",
       "How do you measure whether tuning worked?"],
      "detection-sketch"),
    E("YARA for Defenders",
      ["Explain what YARA identifies and where defenders use it",
       "Read a YARA rule's strings and condition sections",
       "Apply YARA in triage and hunting workflows"],
      ["What is YARA best used for by defenders?",
       "What do the strings and condition sections do?",
       "Where does YARA fit in a hunt?"],
      "hunt-hypothesis"),
    E("Consuming Threat Intelligence",
      ["Distinguish strategic, operational, and tactical intel",
       "Evaluate an intel report's relevance to your environment",
       "Turn an indicator list into defensive action"],
      ["What are the three levels of threat intel?",
       "How do you judge an intel report's relevance?",
       "What do you do with an indicator feed?"],
      "intel-brief"),
    E("Hunt Hypotheses That Falsify",
      ["Write a falsifiable hunt hypothesis",
       "Scope a hunt so it finishes instead of sprawling",
       "Define what evidence would disprove the hypothesis"],
      ["What makes a hunt hypothesis falsifiable?",
       "How does scoping bound a hunt?",
       "What evidence would disprove your hypothesis?"],
      "hunt-hypothesis"),
    E("Baselining the Normal",
      ["Build a behavioral baseline for a system or user group",
       "Spot deviations worth investigating",
       "Document baselines so hunts are repeatable"],
      ["Why is 'normal' the prerequisite for 'suspicious'?",
       "How do you baseline without drowning in data?",
       "What makes a baseline reusable?"],
      "hunt-hypothesis"),
    E("SIEM Workflow Design",
      ["Design a detection-to-triage queue with SLAs",
       "Define escalation criteria",
       "Balance automation with analyst judgment"],
      ["What belongs in a SIEM triage queue?",
       "When does an alert escalate?",
       "Where should automation stop and judgment start?"],
      "triage"),
    E("Advanced Threat Hunting",
      ["Chain multiple hypotheses across attack stages",
       "Hunt without alerts using raw telemetry",
       "Document hunts for detection-engineering handoff"],
      ["How do multi-stage hunts differ from single hunts?",
       "What does alert-free hunting require?",
       "How does a hunt become a detection?"],
      "hunt-hypothesis"),
    E("DFIR: The Responder's Playbook",
      ["Walk the NIST incident lifecycle from preparation to recovery",
       "Run response with evidence integrity intact",
       "Make the first 30 minutes of an incident count"],
      ["What are the incident response phases?",
       "What does evidence integrity require during response?",
       "What matters most in the first 30 minutes?"],
      "triage"),
    E("Timeline Analysis",
      ["Build a super-timeline from multiple sources",
       "Correlate events across hosts",
       "Read attacker narrative from a timeline"],
      ["What is a super-timeline?",
       "How do you correlate events across hosts?",
       "How do you read attacker narrative from timestamps?"],
      "triage"),
    E("Scoping an Incident",
      ["Determine blast radius from evidence, not fear",
       "Decide what is in-scope versus out-of-scope",
       "Communicate scope with explicit confidence levels"],
      ["How do you determine blast radius?",
       "What separates in-scope from out-of-scope?",
       "How do you state scope honestly?"],
      "triage"),
    E("Containment Decisions",
      ["Weigh isolate-now versus observe-longer trade-offs",
       "Choose containment proportionate to confidence",
       "Plan eradication before containing"],
      ["When do you isolate immediately versus keep observing?",
       "What makes containment proportionate?",
       "Why plan eradication before containment?"],
      "tabletop"),
    E("Detection as Code",
      ["Version detections in git like software",
       "Test detections before deployment",
       "Roll back a bad detection safely"],
      ["Why version detections like software?",
       "What should detection testing check?",
       "How do you roll back safely?"],
      "detection-sketch"),
    E("Validating Detections Safely",
      ["Explain defensive validation versus offensive testing",
       "Run atomic, scoped validation checks",
       "Measure detection coverage honestly"],
      ["What is defensive validation?",
       "How do you validate without risking production?",
       "How do you measure coverage honestly?"],
      "detection-sketch"),
    E("The Intelligence Cycle",
      ["Run direction, collection, analysis, dissemination",
       "Write collection requirements that can actually be answered",
       "Disseminate intel the business will use"],
      ["What are the intelligence cycle phases?",
       "What makes a good collection requirement?",
       "How do you write intel people act on?"],
      "intel-brief"),
    E("Vulnerability Management",
      ["Prioritize beyond CVSS: exploitability and asset value",
       "Design a remediation SLA",
       "Track vulnerability metrics that drive action"],
      ["Why is CVSS alone insufficient for prioritization?",
       "How do you set remediation SLAs?",
       "Which vulnerability metrics change behavior?"],
      "hardening-check"),
    E("Hardening Programs",
      ["Apply CIS-style baselines proportionately",
       "Verify hardening with checks, not assumptions",
       "Handle exceptions without eroding the baseline"],
      ["What is a hardening baseline?",
       "How do you verify instead of assume?",
       "How do you handle exceptions safely?"],
      "hardening-check"),
    E("Metrics That Matter",
      ["Choose MTTD, MTTR, coverage, and precision metrics",
       "Avoid vanity metrics",
       "Present security metrics to leadership"],
      ["Which metrics reflect real defensive capability?",
       "What makes a metric vanity?",
       "How do you brief leadership?"],
      "coverage-map"),
    E("Supporting Incident Command",
      ["Describe incident command roles",
       "Communicate upward without causing panic",
       "Keep decision logs during incidents"],
      ["What are the key incident command roles?",
       "How do you brief executives mid-incident?",
       "Why keep a decision log?"],
      "tabletop"),
    E("Purple-Team Thinking (Defensive)",
      ["Extract defensive lessons from exercises",
       "Turn findings into detection and hardening backlogs",
       "Run blameless reviews"],
      ["What does the defensive side gain from joint exercises?",
       "How do findings become backlog?",
       "What makes a review blameless?"],
      "tabletop"),
    E("Designing Tabletops",
      ["Design scenarios that test decisions, not trivia",
       "Facilitate without leading the room",
       "Capture action items that actually get done"],
      ["What makes a tabletop scenario good?",
       "How do you facilitate neutrally?",
       "How do tabletops produce real improvements?"],
      "tabletop"),
    E("Capstone: Full Incident",
      ["Run a complete incident end-to-end",
       "Make scope, containment, and communications calls",
       "Write the after-action report"],
      ["How do the phases connect in a real incident?",
       "Which decisions were hardest and why?",
       "What goes in the after-action report?"],
      "capstone"),
    E("Track A Graduation Review",
      ["Demonstrate cumulative defensive competence",
       "Identify remaining gaps honestly",
       "Commit to a post-academy practice plan"],
      ["What can you now do that you could not on day 1?",
       "Where are you still weak?",
       "What is your 90-day practice plan?"],
      "capstone"),
]

TRACK_B = [  # Platform Intelligence — public sources, original synthesis.
    E("How Assistant Platforms Operate",
      ["Compare interaction models: chat, agent, ambient",
       "Explain capability patterns that recur across platforms",
       "Identify what users actually value and pay for"],
      ["What are the main assistant interaction models?",
       "Which capability patterns recur across platforms?",
       "What do users value most?"],
      "platform-teardown"),
    E("Tool-Use Architectures",
      ["Explain function calling and tool loops",
       "Compare planning approaches across platforms",
       "Identify safety patterns: confirmations, scopes, receipts"],
      ["How does tool use work in agents?",
       "How do platforms plan multi-step tasks?",
       "What safety patterns exist?"],
      "platform-teardown"),
    E("Memory in Agent Platforms",
      ["Distinguish session, working, and long-term memory",
       "Compare memory architectures across platforms",
       "Explain provenance and forgetting"],
      ["What are the layers of agent memory?",
       "How do platforms handle long-term memory?",
       "Why does provenance matter?"],
      "platform-teardown"),
    E("Delegation and Scheduling Patterns",
      ["Compare subagent and orchestration models",
       "Explain scheduled autonomous work",
       "Identify where humans must stay in the loop"],
      ["How do platforms delegate to subagents?",
       "How is scheduled autonomy structured?",
       "Where must humans stay in the loop?"],
      "platform-teardown"),
    E("UX Patterns Worth Adopting",
      ["Deconstruct streaming, transparency, and control UX",
       "Separate information from manipulation",
       "Name patterns LEVI should adopt"],
      ["Which UX patterns build trust?",
       "How do you separate information from pressure?",
       "What should LEVI adopt?"],
      "ux-deconstruction"),
    E("Failure Modes of AI Platforms",
      ["Catalog hallucination, over-autonomy, and injection failures",
       "Explain how platforms mitigate each",
       "Design honest failure UX"],
      ["What are the top AI platform failure modes?",
       "How do leading platforms mitigate them?",
       "What does honest failure UX look like?"],
      "comparison"),
    E("Week 1 Synthesis: The LEVI Difference",
      ["Summarize adopt, adapt, and deliberately-different across week 1",
       "Write LEVI's platform differentiation",
       "Defend the differences with reasons"],
      ["What will LEVI adopt from AI platforms?",
       "What will it adapt?",
       "What will it deliberately do differently, and why?"],
      "comparison"),
    E("SIEM Platforms: Detection Workflows",
      ["Map how SIEMs structure detection to triage",
       "Compare rule management across products",
       "Extract workflow ideas for LEVI"],
      ["How do SIEMs organize detection workflows?",
       "How do products differ in rule management?",
       "What can LEVI borrow?"],
      "platform-teardown"),
    E("SOAR: Automation with Guardrails",
      ["Explain playbook automation models",
       "Identify where SOAR keeps humans in the loop",
       "Compare low-code versus code playbooks"],
      ["How do SOAR playbooks work?",
       "Where is human judgment preserved?",
       "Low-code versus code: what are the trade-offs?"],
      "platform-teardown"),
    E("Bug Bounty Platforms",
      ["Explain scope, triage, and reward mechanics",
       "Compare the major bounty platform models",
       "Extract trust and fairness patterns"],
      ["How do bounty platforms define scope?",
       "How do triage and rewards work?",
       "What builds researcher trust?"],
      "platform-teardown"),
    E("EDR and XDR Platforms",
      ["Explain endpoint telemetry product models",
       "Compare detection versus response emphasis",
       "Identify data-model patterns"],
      ["What do EDR and XDR platforms sell?",
       "Detection versus response: where is the emphasis?",
       "What data models recur?"],
      "platform-teardown"),
    E("Threat Intel Platforms",
      ["Explain intel sharing models",
       "Describe exchange standards and formats",
       "Evaluate trust in shared intel"],
      ["How is threat intel shared?",
       "What standards enable exchange?",
       "How do you trust shared intel?"],
      "platform-teardown"),
    E("Detection Marketplaces",
      ["Explain community rule sharing",
       "Compare curation models",
       "Assess quality signals for shared detections"],
      ["How are detections shared as a marketplace?",
       "How is quality curated?",
       "What signals indicate a good rule?"],
      "comparison"),
    E("Week 2 Synthesis",
      ["Consolidate SecOps platform patterns",
       "Write adopt, adapt, differ for the SOC domain",
       "Prioritize what LEVI builds first"],
      ["What SecOps patterns matter most?",
       "Adopt, adapt, differ for SOC tooling?",
       "What should LEVI build first?"],
      "comparison"),
    E("Retail Trading UX",
      ["Deconstruct portfolio dashboards and watchlists",
       "Identify gamification and urgency manipulation",
       "Separate useful clarity from pressure"],
      ["What makes trading UX clear?",
       "Where does it manipulate the user?",
       "How do you keep clarity without pressure?"],
      "ux-deconstruction"),
    E("Presenting Signals Honestly",
      ["Present confidence and provenance alongside signals",
       "Avoid false precision",
       "Design explicit 'I do not know' states"],
      ["How do you show confidence honestly?",
       "What is false precision?",
       "How do you design for uncertainty?"],
      "ux-deconstruction"),
    E("Portfolio and Watchlist Views",
      ["Explain information hierarchy in portfolio UX",
       "Design progressive disclosure",
       "Let users control detail depth"],
      ["What belongs at the top of a portfolio view?",
       "How does progressive disclosure work?",
       "How do users control detail?"],
      "ux-deconstruction"),
    E("Market Data Platforms",
      ["Explain feeds, latency tiers, and cost structures",
       "Compare retail versus institutional data",
       "Relate findings to LEVI's finance domain"],
      ["How do market data platforms tier their product?",
       "Retail versus institutional: what differs?",
       "What applies to LEVI finance?"],
      "platform-teardown"),
    E("Fintech Trust UX",
      ["Explain disclosures, compliance UX, and consent",
       "Design trust without friction theater",
       "Apply findings to advisory-only finance"],
      ["How do fintech apps build trust?",
       "What is friction theater?",
       "How does this apply to advisory-only tools?"],
      "ux-deconstruction"),
    E("API Platform Patterns",
      ["Explain docs, sandboxes, and versioning as product",
       "Compare developer-experience leaders",
       "Extract patterns for LEVI's own surfaces"],
      ["What makes API docs great?",
       "How do platforms version without breaking trust?",
       "What should LEVI copy?"],
      "platform-teardown"),
    E("Week 3 Synthesis",
      ["Consolidate fintech and market platform lessons",
       "Write adopt, adapt, differ for finance UX",
       "Set LEVI finance UX principles"],
      ["What are LEVI's finance UX principles?",
       "Adopt, adapt, differ?",
       "What will you never do in finance UX?"],
      "comparison"),
    E("Creator Platforms",
      ["Explain content pipelines and monetization",
       "Compare discovery models",
       "Extract packaging and scheduling patterns"],
      ["How do creator platforms structure pipelines?",
       "How does discovery work?",
       "What applies to content operations?"],
      "platform-teardown"),
    E("Distribution and Recommendation",
      ["Explain feed and recommendation mechanics",
       "Discuss feedback loops and their failure modes",
       "Design healthy distribution"],
      ["How do recommendation systems work?",
       "What are the failure modes?",
       "What does healthy distribution look like?"],
      "platform-teardown"),
    E("Community Platforms",
      ["Explain moderation and trust models",
       "Compare governance approaches",
       "Extract safety patterns"],
      ["How do platforms moderate at scale?",
       "What governance models exist?",
       "What safety patterns transfer?"],
      "platform-teardown"),
    E("Platform Business Models",
      ["Explain how platforms capture value",
       "Compare free-core versus paid-layer models",
       "Relate to LEVI's economics: free to produce, valuable, profitable"],
      ["How do platforms make money?",
       "What are the viable free-core models?",
       "How does LEVI's economics compare?"],
      "comparison"),
    E("Mapping the Competitive Landscape",
      ["Map competitors across the three tracks' domains",
       "Identify white space",
       "Write LEVI's moat thesis"],
      ["Who competes in each domain?",
       "Where is the white space?",
       "What is LEVI's moat?"],
      "comparison"),
    E("LEVI's Positioning",
      ["Write a positioning statement per domain",
       "Defend it against alternatives",
       "Name what LEVI will not do"],
      ["How is LEVI positioned?",
       "Why not the alternatives?",
       "What will LEVI not do?"],
      "comparison"),
    E("Build versus Adopt Decisions",
      ["Apply a build-versus-adopt framework",
       "Estimate total cost honestly",
       "Make three real decisions"],
      ["What framework guides build versus adopt?",
       "How do you estimate total cost?",
       "Which three decisions matter most?"],
      "comparison"),
    E("Final Platform Teardown",
      ["Tear down a chosen platform end-to-end",
       "Produce the full adopt, adapt, differ brief",
       "Present findings crisply"],
      ["What is the platform's core loop?",
       "Adopt, adapt, differ?",
       "What is the one insight that matters?"],
      "platform-teardown"),
    E("Track B Graduation Synthesis",
      ["Demonstrate platform-intelligence competence",
       "Present the 30-day teardown portfolio",
       "Commit to an ongoing platform watch"],
      ["What patterns do you now see everywhere?",
       "What is your teardown portfolio?",
       "How will you keep watching?"],
      "capstone"),
]

TRACK_C = [  # LEVI Domain Mastery — operate LEVI's own systems.
    E("The Agent Runtime",
      ["Explain LEVI's tool registry and agentic loop",
       "Run the loop's human-in-the-loop gate",
       "Trace a tool call end-to-end"],
      ["How does the agentic loop work?",
       "Where does human approval gate execution?",
       "How do you trace a tool call?"],
      "module-drill"),
    E("Skills and the Registry",
      ["Explain skill categories and risk tags",
       "Load a skill and inspect its contract",
       "Describe when to create a new skill"],
      ["How are skills categorized?",
       "What is a skill contract?",
       "When should you create one?"],
      "module-drill"),
    E("Scheduling and Automation",
      ["Create a cron and a hook definition",
       "Explain idempotency in scheduled work",
       "Debug a missed run"],
      ["How do crons and hooks differ?",
       "Why does idempotency matter?",
       "How do you debug a missed run?"],
      "module-drill"),
    E("Memory Systems",
      ["Explain the memory store and provenance",
       "Write and retrieve a memory",
       "Apply the growth safety rails"],
      ["How is memory stored?",
       "What is provenance?",
       "What are the growth rails?"],
      "module-drill"),
    E("Sessions and Chat",
      ["Explain session persistence and summarization",
       "Run a chat turn through the loop",
       "Describe the context-compaction rule"],
      ["How do sessions persist?",
       "What happens when context fills?",
       "How does summarization preserve facts?"],
      "module-drill"),
    E("Providers and References",
      ["Explain the provider chain and the identity rule",
       "Add a provider reference",
       "State the references-not-sources doctrine"],
      ["How does provider selection work?",
       "What is the identity rule?",
       "Why references, not sources?"],
      "module-drill"),
    E("Week 1 Drill",
      ["Operate agent, skills, schedule, and memory together",
       "Diagnose a broken automation",
       "Document the fix"],
      ["How do the week-1 systems connect?",
       "How do you diagnose automation failure?",
       "What did you learn?"],
      "orchestration-drill"),
    E("The News Pipeline",
      ["Explain ingest to dated corpus to query",
       "Refresh and query the corpus",
       "Explain why news stays out of training weights"],
      ["How does the news pipeline work?",
       "How do you query the corpus?",
       "Why is news excluded from training?"],
      "module-drill"),
    E("Knowledge Bases",
      ["Query the course and security indexes",
       "Explain the 81-category security catalog",
       "Add a knowledge entry correctly"],
      ["How are knowledge bases organized?",
       "What does the security index cover?",
       "How do you add entries?"],
      "module-drill"),
    E("Demand Intelligence",
      ["Explain five-factor scoring",
       "Score a seeded signal",
       "Defend the honesty guardrails"],
      ["What are the five factors?",
       "How do you score a signal?",
       "Why require a basis note?"],
      "module-drill"),
    E("The Finance Domain",
      ["Explain bars, indicators, and signals",
       "Run scoring on synthetic bars",
       "State the advisory-only boundary"],
      ["How do market signals work?",
       "How do you score synthetic bars?",
       "What is the advisory-only boundary?"],
      "module-drill"),
    E("Bounty Recon Pipeline",
      ["Explain scope-gated recon",
       "Enroll a scope and run recon safely",
       "Read findings and monitor changes"],
      ["How does scope gating work?",
       "What are the recon stages?",
       "How do you monitor for change?"],
      "module-drill"),
    E("The Security Index",
      ["Navigate the 81 categories",
       "Show an attack profile",
       "Explain the defensive-only boundary"],
      ["How is the index organized?",
       "What is an attack profile?",
       "Where is the defensive boundary?"],
      "module-drill"),
    E("Week 2 Drill",
      ["Chain news to demand to finance in one flow",
       "Keep provenance across the chain",
       "Present the result honestly"],
      ["How do intel domains connect?",
       "How is provenance preserved?",
       "What does honest presentation require?"],
      "orchestration-drill"),
    E("King Control Plane",
      ["Explain the manuscript and social workflow",
       "Run preview without posting",
       "State the permission path"],
      ["How does the workflow gate publishing?",
       "What does preview show?",
       "Where is permission required?"],
      "module-drill"),
    E("The Growth Loop",
      ["Explain harvest, reflect, consolidate, journal",
       "Run a dry-run cycle",
       "Read the baby book"],
      ["What are the growth stages?",
       "How does consolidation stay safe?",
       "What is the journal for?"],
      "module-drill"),
    E("Lab and Evals",
      ["Explain clean-room experiments",
       "Run a lab scenario",
       "Read a model card honestly"],
      ["What makes an experiment clean-room?",
       "How do you run a scenario?",
       "How do you read a model card?"],
      "module-drill"),
    E("Plugins and MCP",
      ["Explain the plugin contract",
       "Add an MCP reference",
       "List and inspect plugins"],
      ["What is the plugin contract?",
       "How do references work?",
       "How do you inspect plugins?"],
      "module-drill"),
    E("Operating the Daemon",
      ["Explain the always-on OS layer",
       "Check daemon health",
       "Recover from a stuck service"],
      ["What does the daemon do?",
       "How do you check health?",
       "How do you recover?"],
      "module-drill"),
    E("Hardening LEVI Itself",
      ["Review a module defensively",
       "Apply least privilege",
       "Write a hardening checklist"],
      ["How do you review your own modules?",
       "Where is least privilege violated?",
       "What goes on the checklist?"],
      "design-review"),
    E("Week 3 Drill",
      ["Operate King, growth, lab, and plugins together",
       "Trace a cross-module failure",
       "Write the incident note"],
      ["How do week-3 systems interact?",
       "How do you trace cross-module failure?",
       "What goes in the note?"],
      "orchestration-drill"),
    E("Cross-Domain Orchestration",
      ["Design a multi-domain workflow",
       "Keep each domain's guardrails intact",
       "Produce a unified receipt"],
      ["How do you orchestrate across domains?",
       "How are guardrails preserved?",
       "What is a unified receipt?"],
      "orchestration-drill"),
    E("Decision Traces",
      ["Explain provenance from intent to receipt",
       "Reconstruct a decision from traces",
       "Audit a past automation"],
      ["What is a decision trace?",
       "How do you reconstruct one?",
       "How do you audit automation?"],
      "orchestration-drill"),
    E("Failure Composting",
      ["Explain failure composting: turning failure into lessons",
       "Turn a failure into a lesson",
       "Keep the compost honest"],
      ["How does failure become compost?",
       "What makes composting honest?",
       "When is a failure truly composted?"],
      "orchestration-drill"),
    E("Performance Tuning",
      ["Measure a slow path",
       "Apply one principled optimization",
       "Verify no behavior change"],
      ["How do you find the slow path?",
       "What is a principled optimization?",
       "How do you verify safety?"],
      "module-drill"),
    E("The Operator's Handbook",
      ["Write runbook entries",
       "Define on-call discipline",
       "Document escalation paths"],
      ["What goes in a runbook?",
       "What is on-call discipline?",
       "When do you escalate?"],
      "design-review"),
    E("Policy and Safety Rails",
      ["Enumerate LEVI's binding policies",
       "Test a rail with a probe",
       "Explain fail-closed design"],
      ["What policies bind LEVI?",
       "How do you test a rail?",
       "What does fail-closed mean?"],
      "design-review"),
    E("Final Systems Review",
      ["Map every major subsystem",
       "Name each subsystem's failure mode",
       "Prioritize hardening work"],
      ["What are the major subsystems?",
       "What breaks each?",
       "What do you harden first?"],
      "orchestration-drill"),
    E("Pre-Graduation Integration",
      ["Run a full day of LEVI operations",
       "Keep all guardrails green",
       "Write the operations report"],
      ["Can you operate LEVI for a full day?",
       "Were guardrails ever bypassed?",
       "What does the report show?"],
      "capstone"),
    E("Track C Graduation",
      ["Demonstrate operator competence",
       "Present the systems portfolio",
       "Take the operator's oath: honest limits"],
      ["What can you operate?",
       "What is your portfolio?",
       "What are your honest limits?"],
      "capstone"),
]

TRACK_S = [  # Block 4 — synthesis / sparring, cross-track practicals.
    E("Sparring: First SOC Shift",
      ["Triage a simulated queue across all three tracks",
       "Use LEVI modules in the response",
       "Write the shift report"],
      ["How do you prioritize the queue?",
       "Which LEVI tools helped?",
       "What goes in the shift report?"],
      "sparring-scenario"),
    E("Sparring: Hunt Exercise",
      ["Execute a scoped hunt end-to-end",
       "Falsify or confirm the hypothesis",
       "Hand off a detection"],
      ["What was the hypothesis?",
       "What did the evidence show?",
       "What detection came out of it?"],
      "sparring-scenario"),
    E("Sparring: Teardown Drill",
      ["Tear down a platform in 30 minutes",
       "Extract adopt, adapt, differ",
       "Present in 5 minutes"],
      ["What is the platform's core loop?",
       "Adopt, adapt, differ?",
       "What is the headline insight?"],
      "sparring-scenario"),
    E("Sparring: Detection Duel",
      ["Write a detection",
       "Critique a partner detection",
       "Merge the best of both"],
      ["What does your detection catch?",
       "What is weak in the partner's?",
       "What did the merge improve?"],
      "sparring-scenario"),
    E("Sparring: Triage Race",
      ["Triage 10 alerts in 20 minutes",
       "Defend your priority order",
       "Identify what you deferred and why"],
      ["What was your priority order?",
       "Why?",
       "What did you defer?"],
      "sparring-scenario"),
    E("Sparring: Intel Brief",
      ["Fuse sources into a one-page brief",
       "Brief a decision-maker",
       "Handle a hard question"],
      ["What is the bottom line?",
       "What is the evidence?",
       "How did you handle the hard question?"],
      "sparring-scenario"),
    E("Sparring: Week 1 Review",
      ["Replay the week's hardest moments",
       "Name what broke and why",
       "Set week-2 sparring goals"],
      ["What was hardest?",
       "What broke?",
       "What are your week-2 goals?"],
      "sparring-scenario"),
    E("Sparring: Lateral Movement Hunt",
      ["Hunt across hosts for movement",
       "Correlate identity and endpoint telemetry",
       "Scope the findings"],
      ["Where did movement occur?",
       "How did you correlate?",
       "What is the scope?"],
      "sparring-scenario"),
    E("Sparring: DFIR Tabletop",
      ["Run a tabletop as incident lead",
       "Make containment calls",
       "Capture action items"],
      ["What decisions did you make?",
       "Why?",
       "What are the action items?"],
      "tabletop"),
    E("Sparring: Bounty Platform Teardown",
      ["Tear down bounty platform mechanics",
       "Design a fair triage queue",
       "Present the trust model"],
      ["How do the mechanics work?",
       "What is fair triage?",
       "What builds trust?"],
      "sparring-scenario"),
    E("Sparring: Bounty Triage Drill",
      ["Triage simulated bounty reports",
       "Spot duplicates and out-of-scope reports",
       "Write researcher replies"],
      ["Which reports are valid?",
       "How do you spot duplicates?",
       "What do you tell researchers?"],
      "sparring-scenario"),
    E("Sparring: Detection-as-Code Sprint",
      ["Ship a versioned detection in one session",
       "Test it CI-style",
       "Document the rollout"],
      ["What did you ship?",
       "How did you test?",
       "What is the rollout plan?"],
      "sparring-scenario"),
    E("Sparring: Trading App Teardown",
      ["Tear down a trading app's UX",
       "Separate clarity from manipulation",
       "Write LEVI's finance UX rules"],
      ["Where is the clarity?",
       "Where is the manipulation?",
       "What are LEVI's rules?"],
      "sparring-scenario"),
    E("Sparring: Week 2 Review",
      ["Consolidate intermediate methods",
       "Pressure-test your detections",
       "Set week-3 goals"],
      ["What methods are now solid?",
       "Which detections survived?",
       "What are the week-3 goals?"],
      "sparring-scenario"),
    E("Sparring: Incident Command Sim",
      ["Command a simulated incident",
       "Brief executives twice",
       "Keep the decision log"],
      ["What were the key decisions?",
       "How did the briefings land?",
       "What does the log show?"],
      "sparring-scenario"),
    E("Sparring: Purple Tabletop (Defensive)",
      ["Extract defensive improvements from the exercise",
       "Write detection backlog items",
       "Commit to hardening changes"],
      ["What did the exercise reveal?",
       "What is the detection backlog?",
       "What hardening is committed?"],
      "tabletop"),
    E("Sparring: AI Platform Teardown",
      ["Tear down an AI platform's agent loop",
       "Map its safety patterns",
       "Write LEVI's answer"],
      ["How does its agent loop work?",
       "What safety patterns exist?",
       "What is LEVI's answer?"],
      "platform-teardown"),
    E("Sparring: Vuln Prioritization Drill",
      ["Prioritize 20 vulnerabilities in 30 minutes",
       "Defend the top 5",
       "Name what you accepted as risk"],
      ["What is your top 5?",
       "Why?",
       "What risk did you accept?"],
      "sparring-scenario"),
    E("Sparring: Intel-to-Detection Drill",
      ["Turn an intel report into a detection",
       "Validate it safely",
       "Hand off to production"],
      ["What intel did you use?",
       "What detection resulted?",
       "How was it validated?"],
      "sparring-scenario"),
    E("Sparring: Creator Platform Teardown",
      ["Tear down a creator platform",
       "Map its distribution loop",
       "Apply lessons to content operations"],
      ["What is the distribution loop?",
       "What transfers?",
       "What do we do differently?"],
      "sparring-scenario"),
    E("Sparring: Week 3 Review",
      ["Consolidate advanced application",
       "Run your hardest scenario again",
       "Set final-week goals"],
      ["What is now automatic?",
       "What still needs work?",
       "What are the final-week goals?"],
      "sparring-scenario"),
    E("Capstone: Enterprise Intrusion",
      ["Run the full response across all tracks",
       "Coordinate detection, intel, and comms",
       "Deliver the after-action report"],
      ["How did the tracks combine?",
       "What broke under pressure?",
       "What does the report conclude?"],
      "capstone"),
    E("Capstone: Platform Under Attack",
      ["Defend a platform's trust model",
       "Triage abuse reports",
       "Write the public postmortem"],
      ["How was trust attacked?",
       "What did you triage?",
       "What does the postmortem say?"],
      "capstone"),
    E("Capstone: Full-Stack Teardown",
      ["Tear down an entire platform stack",
       "Produce the investment-grade brief",
       "Defend it under questioning"],
      ["What is the stack's thesis?",
       "What is the brief's recommendation?",
       "How did you defend it?"],
      "capstone"),
    E("Capstone: Adversary Review (Defensive)",
      ["Review detections against new intel",
       "Close the gaps found",
       "Measure coverage honestly"],
      ["What gaps did new intel reveal?",
       "How were they closed?",
       "What is honest coverage now?"],
      "tabletop"),
    E("Capstone: The Operator's Gauntlet",
      ["Operate LEVI under load for the session",
       "Keep every guardrail green",
       "Produce the ops receipt"],
      ["Did guardrails hold?",
       "What degraded?",
       "What does the receipt prove?"],
      "capstone"),
    E("Capstone: Platform War-Game",
      ["War-game LEVI against two competitors",
       "Stress-test the positioning as an analyst",
       "Strengthen the moat"],
      ["How would competitors attack?",
       "Where is LEVI weak?",
       "How is the moat strengthened?"],
      "capstone"),
    E("Capstone: Final Hunt",
      ["Run the hardest hunt of the program",
       "Document every step",
       "Hand off production detections"],
      ["What made this hunt the hardest?",
       "How did you work it?",
       "What detections resulted?"],
      "capstone"),
    E("Capstone: Dress Rehearsal",
      ["Rehearse the graduation assessment",
       "Fix every gap found",
       "Rest and prepare"],
      ["What gaps remain?",
       "How were they fixed?",
       "Are you ready?"],
      "capstone"),
    E("GRADUATION",
      ["Pass the cross-track final assessment",
       "Present the 30-day portfolio",
       "Graduate into continuous practice"],
      ["What did 30 days build?",
       "What are your honest limits?",
       "What comes after graduation?"],
      "graduation"),
]


def build() -> dict:
    for name, track in (("A", TRACK_A), ("B", TRACK_B),
                        ("C", TRACK_C), ("S", TRACK_S)):
        assert len(track) == 30, f"track {name}: {len(track)} != 30"
        for i, day in enumerate(track, 1):
            for key in ("title", "objectives", "key_questions", "exercise_type"):
                assert day.get(key), f"track {name} day {i}: missing {key}"
    return {
        "program": "LEVI Boot Camp — 30-day, 24/7 defensive analyst, platform "
                   "intelligence, and LEVI domain mastery program",
        "days": 30,
        "blocks_per_day": 4,
        "sessions_total": 120,
        "block_map": {"1": "A", "2": "B", "3": "C", "4": "S"},
        "track_names": {
            "A": "Defensive Security Analyst",
            "B": "Platform Intelligence",
            "C": "LEVI Domain Mastery",
            "S": "Synthesis Sparring (cross-track)",
        },
        "track_boundaries": {
            "A": "Defensive-only. Detection, analysis, hardening. "
                 "No offensive instruction content, ever.",
            "B": "Public sources only. Original LEVI synthesis, never copied text.",
            "C": "Operate LEVI's own systems. Advisory-only where money or "
                 "publishing is involved.",
            "S": "Cross-track practicals. Inherits the strictest boundary of "
                 "every track involved (defensive-only for security content).",
        },
        "weeks": WEEKS,
        "tracks": {
            "A": {"name": "Defensive Security Analyst",
                  "days": {str(i + 1): d for i, d in enumerate(TRACK_A)}},
            "B": {"name": "Platform Intelligence",
                  "days": {str(i + 1): d for i, d in enumerate(TRACK_B)}},
            "C": {"name": "LEVI Domain Mastery",
                  "days": {str(i + 1): d for i, d in enumerate(TRACK_C)}},
            "S": {"name": "Synthesis Sparring (cross-track)",
                  "days": {str(i + 1): d for i, d in enumerate(TRACK_S)}},
        },
    }


def main(argv: list[str]) -> int:
    out = Path(argv[argv.index("--out") + 1]) if "--out" in argv else HERE / "syllabus.json"
    data = build()
    out.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out}: 30 days x 4 blocks = 120 sessions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
