export type GenreCategory =
  | "core_classical"
  | "signature_lattice"
  | "hybrid"
  | "atmosphere_structure"
  | "world_society"
  | "mind_identity"
  | "form_forward"
  | "lwp_specialty"
  | "mainstream_extended";

export const GENRE_CATEGORIES: { id: GenreCategory; label: string }[] = [
  { id: "core_classical", label: "Core" },
  { id: "signature_lattice", label: "Signature" },
  { id: "hybrid", label: "Hybrid" },
  { id: "atmosphere_structure", label: "Atmosphere" },
  { id: "world_society", label: "World" },
  { id: "mind_identity", label: "Mind" },
  { id: "form_forward", label: "Form" },
  { id: "lwp_specialty", label: "L.W.P." },
  { id: "mainstream_extended", label: "Mainstream" },
];

export const GENRES: { id: string; category: GenreCategory }[] = [
  { id: "literary", category: "core_classical" },
  { id: "thriller", category: "core_classical" },
  { id: "psychological_thriller", category: "core_classical" },
  { id: "horror", category: "core_classical" },
  { id: "mystery", category: "core_classical" },
  { id: "noir", category: "core_classical" },
  { id: "dystopian", category: "core_classical" },
  { id: "sci_fi", category: "core_classical" },
  { id: "gothic", category: "core_classical" },
  { id: "romance", category: "core_classical" },
  { id: "romance_erotic", category: "core_classical" },
  { id: "comedy", category: "core_classical" },
  { id: "script", category: "core_classical" },
  { id: "suspense", category: "core_classical" },
  { id: "emotional", category: "core_classical" },
  { id: "humor", category: "core_classical" },
  { id: "systems_horror", category: "signature_lattice" },
  { id: "memory_thriller", category: "signature_lattice" },
  { id: "consent_dystopia", category: "signature_lattice" },
  { id: "lattice_gothic", category: "signature_lattice" },
  { id: "post_privacy_noir", category: "signature_lattice" },
  { id: "trauma_recursion", category: "signature_lattice" },
  { id: "eco_psychic", category: "signature_lattice" },
  { id: "speculative_literary", category: "hybrid" },
  { id: "cascade_realism", category: "hybrid" },
  { id: "cosmic_horror", category: "atmosphere_structure" },
  { id: "body_horror", category: "atmosphere_structure" },
  { id: "folk_horror", category: "atmosphere_structure" },
  { id: "occult_mystery", category: "atmosphere_structure" },
  { id: "conspiracy_thriller", category: "atmosphere_structure" },
  { id: "espionage", category: "atmosphere_structure" },
  { id: "crime", category: "atmosphere_structure" },
  { id: "hardboiled", category: "atmosphere_structure" },
  { id: "surrealism", category: "atmosphere_structure" },
  { id: "magical_realism", category: "atmosphere_structure" },
  { id: "absurdist", category: "atmosphere_structure" },
  { id: "parable", category: "atmosphere_structure" },
  { id: "climate_fiction", category: "world_society" },
  { id: "solarpunk", category: "world_society" },
  { id: "cyberpunk", category: "world_society" },
  { id: "biopunk", category: "world_society" },
  { id: "hopepunk", category: "world_society" },
  { id: "alternate_history", category: "world_society" },
  { id: "political_thriller", category: "world_society" },
  { id: "institutional_drama", category: "world_society" },
  { id: "workplace_dystopia", category: "world_society" },
  { id: "surveillance_state", category: "world_society" },
  { id: "collapse_fiction", category: "world_society" },
  { id: "migration_epic", category: "world_society" },
  { id: "identity_thriller", category: "mind_identity" },
  { id: "double_life", category: "mind_identity" },
  { id: "unreliable_memoir", category: "mind_identity" },
  { id: "found_footage_prose", category: "mind_identity" },
  { id: "epistolary", category: "mind_identity" },
  { id: "confessional", category: "mind_identity" },
  { id: "grief_narrative", category: "mind_identity" },
  { id: "addiction_realism", category: "mind_identity" },
  { id: "neurodivergent_lit", category: "mind_identity" },
  { id: "possession_drama", category: "mind_identity" },
  { id: "mosaic_novel", category: "form_forward" },
  { id: "braided_narrative", category: "form_forward" },
  { id: "choral_novel", category: "form_forward" },
  { id: "documentary_fiction", category: "form_forward" },
  { id: "metafiction", category: "form_forward" },
  { id: "antinovel", category: "form_forward" },
  { id: "constraint_fiction", category: "form_forward" },
  { id: "procedural_lyric", category: "form_forward" },
  { id: "attention_economy_horror", category: "lwp_specialty" },
  { id: "platform_gothic", category: "lwp_specialty" },
  { id: "data_haunting", category: "lwp_specialty" },
  { id: "algorithmic_fate", category: "lwp_specialty" },
  { id: "scar_liturgy", category: "lwp_specialty" },
  { id: "continuity_horror", category: "lwp_specialty" },
  { id: "gold_path_epic", category: "lwp_specialty" },
  { id: "breaker_tragedy", category: "lwp_specialty" },
  { id: "daemon_comedy", category: "lwp_specialty" },
  { id: "interpenetration_romance", category: "lwp_specialty" },
  { id: "drama", category: "mainstream_extended" },
  { id: "dark_comedy", category: "mainstream_extended" },
  { id: "romantic_comedy", category: "mainstream_extended" },
  { id: "family_drama", category: "mainstream_extended" },
  { id: "historical_fiction", category: "mainstream_extended" },
  { id: "literary_fiction", category: "mainstream_extended" },
  { id: "young_adult", category: "mainstream_extended" },
  { id: "adventure", category: "mainstream_extended" },
  { id: "action", category: "mainstream_extended" },
  { id: "western", category: "mainstream_extended" },
  { id: "war", category: "mainstream_extended" },
  { id: "sports", category: "mainstream_extended" },
  { id: "slice_of_life", category: "mainstream_extended" },
  { id: "coming_of_age", category: "mainstream_extended" },
  { id: "tragedy", category: "mainstream_extended" },
  { id: "melodrama", category: "mainstream_extended" },
  { id: "satire", category: "mainstream_extended" },
  { id: "farce", category: "mainstream_extended" },
  { id: "whodunit", category: "mainstream_extended" },
  { id: "cozy_mystery", category: "mainstream_extended" },
];

if (GENRES.length !== 97) {
  throw new Error(`Genre integrity: expected 97, got ${GENRES.length}`);
}

export function labelGenre(id: string) {
  return id.replaceAll("_", " ");
}
