"""SI core: LEVI skill scaffolds from a declared name + capability.

``scaffold_skill(name, capability)`` returns ``{"ok", "name", "files",
"errors"}`` where ``files`` is a ``{path: content}`` map ready for
``levi.revival.omega.materialize`` — three files:

- ``<name>/SKILL.md`` — LEVI's skill frontmatter + a honestly-labeled
  scaffold body (this is a scaffold, not a working skill).
- ``<name>/skill.py`` — stdlib-only executable stub with the honest
  label in its docstring.
- ``<name>/tests/test_<name>.py`` — a test skeleton that checks the
  scaffold's own structure and leaves a clearly-marked TODO for the
  real procedure's tests.

Everything is pure scaffolding: the honest "scaffold, not a skill"
label appears in every generated file, and an invalid name is refused
instead of sanitized (silently renaming a skill hides intent — pick a
real slug).
"""

from __future__ import annotations

import re
from typing import Any, Dict, List

ORIGIN = "levi-revival-omega/si/skill-core"

_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")

SCAFFOLD_BANNER = (
    "SCAFFOLD — NOT A WORKING SKILL. Generated by LEVI revival/omega; "
    "fill in the real procedure, then remove this banner."
)


def _yaml_str(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip().replace('"', "'")


def _skill_md(name: str, capability: str) -> str:
    return f"""---
skill_id: "{name}"
name: "{_yaml_str(name.replace("-", " ").replace("_", " ").title())}"
description: "{_yaml_str(capability)}"
version: "0.1.0-scaffold"
risk: "info"
permissions: []
requires_confirmation: false
tags: ["scaffold", "revival", "omega"]
source: "{ORIGIN}"
scaffold: true
---
# {name}

> **{SCAFFOLD_BANNER}**

## Declared capability

{_yaml_str(capability)}

## Purpose

*Unwritten.* This file is a scaffold: write one paragraph describing what
this skill does, when to use it, and what it never does.

## Steps

1. Parse the request arguments (`python skill.py --help`).
2. Do the work locally — local-first, stdlib only, no paid APIs.
3. Return a short human-readable summary.

## Output contract

- On success: one-line summary plus the result payload.
- On failure: a clear reason and what to do next.

## Operating rules

1. Never collect or store credentials (keys, secrets, passwords, tokens).
2. Never send user data off-machine; local-first always.
3. Defensive only — detection, analysis, hardening. Nothing offensive.

## Honesty notes

- Risk `info` is a starter guess — verify before real use.
- A skill that cannot explain itself in one line is not ready.
- Remove the scaffold banner only when the procedure below is real.
"""


def _skill_py(name: str, capability: str) -> str:
    return f'''"""SCAFFOLD — NOT A WORKING SKILL. {name} (levi-revival-omega).

Declared capability: {_yaml_str(capability)}

Fill in run_skill() with the real procedure, then remove the scaffold
banner. Stdlib only: no network, no credentials, no paid APIs.
"""
from __future__ import annotations

import argparse
import json
import sys

SKILL_ID = "{name}"
_SCAFFOLD = True  # flip to False when run_skill() is real


def run_skill(task: str) -> dict:
    """Do the skill's work locally and return a result payload."""
    if _SCAFFOLD:
        return {{
            "skill": SKILL_ID,
            "task": task,
            "summary": f"SCAFFOLD: {{SKILL_ID}} has no real procedure yet",
            "ok": False,
            "scaffold": True,
        }}
    return {{"skill": SKILL_ID, "task": task, "summary": "", "ok": True}}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog=SKILL_ID, description="SCAFFOLD: " + SKILL_ID
    )
    parser.add_argument("task", nargs="?", default="", help="the task")
    parser.add_argument("--json", action="store_true",
                        help="print the raw result payload")
    args = parser.parse_args(argv)
    result = run_skill(args.task)
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result["summary"])
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def _test_skeleton_py(name: str, capability: str) -> str:
    return f'''"""Test skeleton for the {name} skill — SCAFFOLD, not a real suite.

Generated by LEVI revival/omega ({ORIGIN}). These tests check the
scaffold's own structure so a half-built skill can't pretend to be
finished. Add real procedure tests below and delete the scaffold-only
markers when the skill is real.
"""

import ast

import pytest

from levi.revival.omega.skill_gen import scaffold_skill

NAME = "{name}"
CAPABILITY = r"""{_yaml_str(capability)}"""


def _files():
    result = scaffold_skill(NAME, CAPABILITY)
    assert result["ok"], result["errors"]
    return result["files"]


def test_scaffold_files_present():
    files = _files()
    assert f"{{NAME}}/SKILL.md" in files
    assert f"{{NAME}}/skill.py" in files
    assert f"{{NAME}}/tests/test_{{NAME.replace('-', '_')}}.py" in files


def test_scaffold_label_present_everywhere():
    files = _files()
    for path, content in files.items():
        assert "SCAFFOLD" in content, f"{{path}} lost its scaffold label"


def test_skill_py_parses():
    files = _files()
    ast.parse(files[f"{{NAME}}/skill.py"])


def test_scaffold_reports_not_ok():
    # A scaffold must never claim to work.
    files = _files()
    namespace: dict = {{}}
    exec(compile(files[f"{{NAME}}/skill.py"], "skill.py", "exec"), namespace)
    result = namespace["run_skill"]("probe")
    assert result["ok"] is False
    assert result["scaffold"] is True


@pytest.mark.skip(reason="scaffold: implement the real procedure, then unskip")
def test_real_procedure():
    raise AssertionError("TODO: write the real procedure's tests")
'''


def scaffold_skill(name: str, capability: str) -> Dict[str, Any]:
    """Build the three-file scaffold; ``ok`` is False with reasons if refused.

    Never raises on bad input — the refusal is part of the return value so
    callers (and the CLI) can report it plainly.
    """
    errors: List[str] = []
    if not isinstance(name, str) or not _NAME_RE.match(name or ""):
        errors.append(
            f"invalid skill name {name!r}: use a slug "
            "(lowercase letters, digits, dashes, underscores)"
        )
    if not isinstance(capability, str) or not capability.strip():
        errors.append("capability must be a non-empty string")
    if errors:
        return {"ok": False, "name": name, "files": {}, "errors": errors}
    module = name.replace("-", "_")
    files = {
        f"{name}/SKILL.md": _skill_md(name, capability),
        f"{name}/skill.py": _skill_py(name, capability),
        f"{name}/tests/test_{module}.py": _test_skeleton_py(name, capability),
    }
    return {"ok": True, "name": name, "files": files, "errors": []}
