"""Cybrus — LEVI's own Security & Identity Layer (LEVI-original).

Alpha is the Creation Lab, Omega is the Operating Platform, Cybrus is the
Security & Identity layer: account identities, a credential factory, an
encrypted-at-rest credential vault, and a scoped token engine.

Identity law: this package is LEVI-only. No provider branding, no "powered
by" claims, no external identity services inside the core — references to
outside providers are comparisons for study, never sources LEVI draws on.

Defensive, local, and stdlib-only: no network, no telemetry, no hardcoded
secrets. All state lives under ``~/.levi/cybrus/`` (``LEVI_HOME`` env
override honored, same convention as the rest of the LEVI tree).

Crypto posture:
- ``CredentialVault`` prefers ``cryptography``'s Fernet (AES-128-CBC +
  HMAC-SHA256, authenticated encryption). Where ``cryptography`` is absent
  it falls back to a clearly-labeled stdlib construction
  (PBKDF2-HMAC-SHA256 key derivation, HMAC-SHA256 counter-mode stream
  cipher, HMAC authentication, verify-then-decrypt) — documented in
  ``vault.py`` as fallback-grade, NOT AES. The instance reports which
  backend it is using via ``vault.backend``.
- Account passwords generated by ``AccountFactory`` are never persisted in
  plaintext: only salted PBKDF2-HMAC-SHA256 hash references are stored.
- API tokens are stored as SHA-256 hashes; the plaintext token is returned
  exactly once at issuance/rotation.
"""

from __future__ import annotations

from levi.cybrus._paths import cybrus_dir
from levi.cybrus.factory import AccountFactory
from levi.cybrus.identity import (
    IdentityStore,
    TierError,
    is_founder,
    require_founder,
)
from levi.cybrus.router import RouteError, RouteRefused, RouteRegistry
from levi.cybrus.tokens import TokenEngine, TokenError
from levi.cybrus.vault import (
    AutoLockVault,
    CredentialVault,
    IdentityVault,
    OAuthError,
    OAuthVault,
    VaultError,
    VaultLockedError,
    generate_password,
)

__all__ = [
    "AccountFactory",
    "AutoLockVault",
    "CredentialVault",
    "IdentityStore",
    "IdentityVault",
    "is_founder",
    "OAuthError",
    "OAuthVault",
    "RouteError",
    "RouteRefused",
    "RouteRegistry",
    "TierError",
    "require_founder",
    "TokenEngine",
    "TokenError",
    "VaultError",
    "VaultLockedError",
    "cybrus_dir",
    "generate_password",
]
